(function(){
 'use strict';const M=SphereMath,$=id=>document.getElementById(id);
 let lastPreviewDraw=-Infinity,previewFps=30;
 let state=M.defaultState(),renderer,dirty=true,capturing=false,last=performance.now(),hudTime=0,renderCost=0,toastTimer,keys=new Set(),drag=null;
 const viewport=$('viewport'),canvas=$('view');
 try{const saved=Number(localStorage.getItem('sphere-preview-fps'));if([15,30,60].includes(saved))previewFps=saved;}catch{}
 $('previewFps').value=String(previewFps);$('previewFps').onchange=()=>{previewFps=Number($('previewFps').value);try{localStorage.setItem('sphere-preview-fps',String(previewFps));}catch{}dirty=true;};
 try{renderer=new SphereRenderer(canvas);}catch(e){$('error').hidden=false;$('error').textContent=e.message;return;}
 function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),4500);}
 const distance=v=>!Number.isFinite(v)?'Beyond the shell':v>=1e6?(v/1e6).toFixed(3)+' million km':v.toLocaleString(undefined,{maximumFractionDigits:1})+' km';
 const timeLabel=v=>{const sign=v<0?'−':'',s=Math.floor(Math.abs(v));return sign+[Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(x=>String(x).padStart(2,'0')).join(':');};
 const transforms={radius:1e6,breachDiameter:1e6};
 const fields=['radius','starRadius','luminosity','breachEnabled','breachDiameter','breachLat','breachLon','breachRoughness','surfaceStyle','shadeEnabled','shadeAltitude','shadeDiameter','shadeOffset','shadeDamage','shadeSpeed','shellshine','atmosphere','seed','starfield','fov','speed','projection','viewMode','grid','exposure','timeRate','quality'];
 function updateOutput(){$('starScale').textContent=new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(state.starRadius)+' km radius = '+new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(state.starRadius*2)+' km across';for(const k of ['fov','exposure','shellshine','atmosphere','shadeOffset','shadeDamage','breachRoughness']){const el=$(k+'Value');if(!el)continue;el.textContent=k==='fov'?state.fov+'°':k==='exposure'?state.exposure.toFixed(1)+' stops':k==='shadeOffset'?state.shadeOffset.toFixed(2)+' radii':Math.round(state[k]*100)+'%';}}
 function syncCameraFields(){const ll=M.latlon(state.position);$('cameraLat').value=ll[0].toFixed(5);$('cameraLon').value=ll[1].toFixed(5);$('cameraAltitude').value=(state.radius-M.length(state.position)).toFixed(3);$('cameraAltitude').max=state.radius-state.starRadius*1.02;}
 function sync(){for(const k of fields){const el=$(k);if(el.type==='checkbox')el.checked=state[k];else {const value=String(state[k]/(transforms[k]||1));if(el.tagName==='SELECT'){const str=typeof state[k]==='string'?state[k]:value;if(![...el.options].some(o=>o.value===str)){const op=document.createElement('option');op.value=str;op.textContent=str+' · custom';el.append(op);}el.value=str;}else el.value=value;}}
  syncCameraFields();updateOutput();$('timeSlider').value=M.clamp(state.time,state.collection?-259200:-36000,state.collection?259200:36000);$('play').textContent=state.playing?'Ⅱ':'▶';$('stateIndicator').textContent=state.playing?'RUNNING':'PAUSED';$('wholeArea').textContent=(state.radius/M.AU).toFixed(3)+' AU radius';document.querySelector('.panel-foot span').textContent=(Math.pow(state.radius/6371,2)/1e6).toFixed(1)+' million Earth surfaces';dirty=true;hudTime=0;window.dispatchEvent(new Event('sphere-state-synced'));
 }
 function chooseTab(name){document.querySelectorAll('[data-tab]').forEach(el=>{el.classList.toggle('active',el.dataset.tab===name);el.setAttribute('aria-selected',String(el.dataset.tab===name));});document.querySelectorAll('.tab-panel').forEach(el=>el.hidden=el.id!==name);if(name==='camera')syncCameraFields();}
 document.querySelectorAll('[data-tab]').forEach(el=>el.addEventListener('click',()=>chooseTab(el.dataset.tab)));
 for(const k of fields){const el=$(k);el.addEventListener(el.type==='range'?'input':'change',()=>{
  const before=structuredClone(state);let value=el.type==='checkbox'?el.checked:el.tagName==='SELECT'&&['projection','viewMode','surfaceStyle'].includes(k)?el.value:Number(el.value)*(transforms[k]||1);
  state[k]=value;
  if(k==='radius')state.position=M.mul(before.position,value/before.radius);
  try {const wasPlaying=state.playing;state=M.validate(state);state.playing=wasPlaying;}
  catch(e){state=before;sync();toast(e.message);return;}
  updateOutput();dirty=true;if(k==='radius')sync();if(k==='projection')toast(value==='panorama'?'360° panorama: poles stretch in this flat projection.':'Photographic perspective restored.');
 });}
 document.querySelectorAll('summary .toggle').forEach(el=>el.addEventListener('click',e=>e.stopPropagation()));
 function setLook(f,up=[0,1,0]){const b=M.basis(f,up);state.forward=b.f;state.up=b.u;dirty=true;}
 function moved(){if($('viewTitle').textContent!=='Free survey'){$('viewTitle').textContent='Free survey';document.querySelectorAll('[data-preset]').forEach(el=>el.classList.remove('selected'));}window.dispatchEvent(new Event('sphere-view-changed'));}
 function preset(name,{stage=false}={}){const prior=structuredClone(state);state=stage?M.defaultState():structuredClone(state);
  if(name==='interior'){state.position=[0,0,state.radius*.5];setLook([0,0,1]);state.fov=105;}
  if(name==='breach'){const n=M.axis(state.breachLat,state.breachLon);state.position=M.mul(n,state.radius*.60);setLook(n);state.fov=100;state.speed=100000;}
  if(name==='shade'){state.position=[0,0,state.radius-300];state.shadeOffset=0;setLook([-.65,0,-1]);state.fov=95;state.speed=1000;state.exposure=.7;}
  if(name==='dawn'){state.position=[0,0,state.radius-1];state.shadeOffset=1;setLook([.24,.07,-1]);state.fov=100;state.atmosphere=1;state.exposure=.2;state.speed=10;}
  if(stage){state.antialias=prior.antialias;state.shadowSamples=prior.shadowSamples;state.stationSamples=prior.stationSamples;state.quality=prior.quality;}
  if(!stage){const pose={position:state.position,forward:state.forward,up:state.up};state={...prior,...pose};}window.dispatchEvent(new Event('sphere-view-changed'));
  const titles={interior:'The interior',breach:'The breach',shade:'Under the shade',dawn:'First light'};$('viewTitle').textContent=titles[name];document.querySelectorAll('[data-preset]').forEach(el=>el.classList.toggle('selected',el.dataset.preset===name));sync();viewport.focus({preventScroll:true});
 }
 document.querySelectorAll('[data-preset]').forEach(el=>el.addEventListener('click',()=>preset(el.dataset.preset)));
 document.querySelectorAll('[data-turn]').forEach(el=>el.onclick=()=>{if(capturing)return;const b=M.basis(state.forward,state.up),axis=el.dataset.turn==='yaw'?b.u:el.dataset.turn==='pitch'?b.r:b.f,angle=M.radians(Number($('rotationStep').value))*Number(el.dataset.sign);setLook(M.rotate(b.f,axis,angle),M.rotate(b.u,axis,angle));moved();});
 $('levelCamera').onclick=()=>{if(capturing)return;const up=M.mul(M.norm(state.position),-1);if(Math.abs(M.dot(up,state.forward))>.999){toast('Looking almost straight up or down: use Roll to choose an orientation.');return;}setLook(state.forward,up);moved();};
 $('faceSurface').onclick=()=>{setLook(M.norm(state.position));moved();};$('faceStar').onclick=()=>{setLook(M.mul(M.norm(state.position),-1));moved();};
 $('inspectBelow').onclick=()=>{setLook(M.norm(state.position));moved();toast('Looking toward the nearby surface. Detail follows the distance to what you see.');};
 $('moveCamera').onclick=()=>{const lat=Number($('cameraLat').value),lon=Number($('cameraLon').value),alt=Number($('cameraAltitude').value);if(![lat,lon,alt].every(Number.isFinite)||Math.abs(lat)>90||Math.abs(lon)>180||alt<1||alt>=state.radius-state.starRadius*1.02){toast('Choose a latitude ±90°, longitude ±180°, and altitude inside the shell and outside the star.');return;}state.position=M.mul(M.axis(lat,lon),state.radius-alt);syncCameraFields();dirty=true;moved();toast('Camera moved.');};
 $('play').onclick=()=>{state.playing=!state.playing;sync();};$('resetTime').onclick=()=>{state.time=0;state.playing=false;sync();};
 $('timeSlider').oninput=e=>{state.time=Number(e.target.value);state.playing=false;sync();};
 $('togglePanel').onclick=()=>{document.body.classList.toggle('panel-hidden');dirty=true;};
 $('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await viewport.requestFullscreen();}catch{toast('This browser did not allow full-screen mode.');}dirty=true;};
 $('helpButton').onclick=()=>{keys.clear();$('guide').showModal();};$('closeGuide').onclick=()=>$('guide').close();
 viewport.addEventListener('pointerdown',e=>{if(e.target!==canvas)return;viewport.focus({preventScroll:true});drag={x:e.clientX,y:e.clientY,id:e.pointerId};canvas.setPointerCapture(e.pointerId);});
 canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;const b=M.basis(state.forward,state.up),yaw=-dx*.003,pitch=-dy*.003;let f=M.rotate(b.f,b.u,yaw),r=M.norm(M.cross(f,b.u));f=M.rotate(f,r,pitch);state.up=M.norm(M.rotate(b.u,r,pitch));state.forward=M.norm(f);moved();dirty=true;});
 canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('lostpointercapture',()=>drag=null);
 viewport.addEventListener('wheel',e=>{if(e.target!==canvas)return;e.preventDefault();state.speed=M.clamp(state.speed*Math.exp(-e.deltaY*.0015),1,3e7);dirty=true;hudTime=0;},{passive:false});
 window.addEventListener('keydown',e=>{if($('guide').open||/INPUT|SELECT|TEXTAREA|BUTTON/.test(e.target.tagName))return;if(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ShiftLeft','ShiftRight'].includes(e.code)){keys.add(e.code);e.preventDefault();}if(e.code==='KeyH'){document.body.classList.toggle('clean');}if(e.code==='Space'){e.preventDefault();state.playing=!state.playing;sync();}});
 window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();drag=null;});document.addEventListener('visibilitychange',()=>{keys.clear();last=performance.now();dirty=true;});
 new ResizeObserver(()=>dirty=true).observe(viewport);
 let bookmarks=[];try{const stored=JSON.parse(localStorage.getItem('sphere-bookmarks-v1')||'[]');if(Array.isArray(stored))bookmarks=stored.filter(x=>typeof x.name==='string'&&x.state).slice(0,50);}catch{}
 function storeBookmarks(){try{localStorage.setItem('sphere-bookmarks-v1',JSON.stringify(bookmarks));}catch{toast('Browser storage is unavailable. Export a scene file to keep this view.');}}
 function showBookmarks(){const box=$('bookmarks');box.replaceChildren();for(let i=0;i<bookmarks.length;i++){const row=document.createElement('div');row.className='bookmark-row';const go=document.createElement('button');go.className='secondary';go.textContent=bookmarks[i].name;go.onclick=()=>{try{state=M.validate(bookmarks[i].state);$('viewTitle').textContent=bookmarks[i].name;sync();}catch(e){toast(e.message);}};const del=document.createElement('button');del.className='quiet';del.textContent='×';del.setAttribute('aria-label','Delete '+bookmarks[i].name);del.onclick=()=>{bookmarks.splice(i,1);storeBookmarks();showBookmarks();};row.append(go,del);box.append(row);}}
 $('saveBookmark').onclick=()=>{const name=$('bookmarkName').value.trim()||$('viewTitle').textContent;if(bookmarks.length>=50){toast('You have 50 viewpoints. Export some scenes or remove an old viewpoint.');return;}bookmarks.push({name,state:structuredClone(state)});storeBookmarks();showBookmarks();toast('Viewpoint saved in this browser.');};
 function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
 const assumptions={collection:'Optional Collection study v1: three prescribed shade routes, 18 intact/12 surviving shades with selectable planar disk, square, curved spherical-cap or trimmed-cap geometry, six analytic elliptical wounds, two stellar-service rings. Layout is provisional. ShellShine uses 192 equal-area samples of macro albedo and direct light, one diffuse bounce with adjustable strength. Direct occlusion uses seven or nineteen shared stellar samples without the station, or a selectable 19/64/128/256 common sample set with the station enabled, with receiver self-exclusion. Trimmed caps have planar side cuts parallel to travel; the width is adjustable. On supported GPUs, linear half-float radiance is filtered before exposure and SDR tone mapping. Unsupported GPUs retain display-colour supersampling. Smooth edges adds an optional contrast-directed display filter; it can soften detail and is not geometric coverage integration. Construction texture pitches are fixed in kilometres and filtered with footprint. Surface detail, haze, shade penumbrae and damage are approximate. No mirror delivery, concealment, ablation, orbital evolution or light travel time is simulated.',geometry:'Analytic inner sphere and star; spherical-cap breach with optional defined fractured edge; thin planar shade with optional circular notch. CPU double precision; normalized GPU highp float with stable near-shell root and camera-relative shade coordinates.',lighting:'Direct stellar illumination with sampled shade penumbra. Original studies use uniform fill; Collection study uses a sampled macro-albedo first-bounce estimate with user strength. Approximate local atmospheric scattering only. No solved global multiple scattering or calibrated photometry.',surface:'Deterministic regional atlas with filtered, world-anchored detail bands (or legacy albedo) on a smooth shell; no local relief, populated worlds or detailed terrain.',dynamics:'Free camera; prescribed straight shade pass. Artificial gravity, support, containment and propulsion assumed. No orbit, climate or material-strength model.',stars:'External stars are illustrative and fixed, not an astronomical catalogue.'};
 function record(extra={}){return M.sceneRecord(state,{application:'The Sphere Observatory 0.8',units:'kilometres, seconds, degrees; luminosity in solar units',assumptions,...extra});}
 $('saveScene').onclick=()=>download(new Blob([JSON.stringify(record(),null,2)],{type:'application/json'}),'sphere-scene.json');
 $('loadScene').onclick=()=>$('sceneFile').click();$('sceneFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>1000000)throw Error('Scene files must be smaller than 1 MB.');const parsed=JSON.parse(await file.text());if(parsed.format!=='sphere-observatory'||parsed.version!==1)throw Error('This file is not a supported Sphere scene.');state=M.validate(parsed.state);$('viewTitle').textContent='Imported viewpoint';sync();toast('Scene restored.');}catch(err){toast('Could not import: '+err.message);}finally{e.target.value='';}};
 async function capture(){if(capturing)return;capturing=true;const button=$('capture');button.disabled=true;button.textContent='Rendering photograph…';const wasPlaying=state.playing;state.playing=false;keys.clear();const snapshot=structuredClone(state);const width=Number($('exportSize').value),height=Math.round(width/(state.projection==='panorama'?2:16/9));
  try {await new Promise(resolve=>requestAnimationFrame(resolve));if(width>renderer.gl.getParameter(renderer.gl.MAX_RENDERBUFFER_SIZE))throw Error('That resolution is above this GPU’s limit. Choose a smaller photograph.');renderer.draw(snapshot,width,height,{exportFrame:true});const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('The browser could not encode the image.');const bytes=new Uint8Array(await blob.arrayBuffer());const meta=M.sceneRecord(snapshot,{application:'The Sphere Observatory 0.8',units:'km, seconds, degrees',image:{width,height,render:renderer.renderInfo,projection:state.projection,horizontalFieldOfView:state.projection==='panorama'?360:state.fov},assumptions});const enc=new TextEncoder();const zip=SphereZip([['photograph.png',bytes],['scene.json',enc.encode(JSON.stringify(meta,null,2))],['READ-ME.txt',enc.encode('The Sphere Observatory\nImport scene.json to restore this photograph.\nGeometry is analytic; light transport and surface appearance are approximations. See the assumptions in scene.json.\nAll work is local. No generative image processing was used.\n')]]);download(zip,'sphere-photograph-'+new Date().toISOString().replace(/[:.]/g,'-')+'.zip');toast('Photograph and scene settings exported together.');}
  catch(e){toast('Photograph failed: '+e.message);}finally{capturing=false;state.playing=wasPlaying;button.disabled=false;button.innerHTML='Take photograph <span>↗</span>';dirty=true;last=performance.now();}}
 $('capture').onclick=capture;
 function hud(){const starAngle=2*M.degrees(Math.asin(M.clamp(state.starRadius/M.length(state.position),0,1))),target=M.trace(state.position,state.forward,state);$('altitudeReadout').textContent=distance(state.radius-M.length(state.position));$('starReadout').textContent=starAngle.toFixed(4)+'°';$('sunReadout').textContent=Math.round(M.sunVisibility(state.position,state,256)*100)+'%';$('speedReadout').textContent=distance(state.speed)+'/s';$('targetName').textContent=target.kind;$('targetDistance').textContent=distance(target.distance);$('timeReadout').textContent=timeLabel(state.time);if(document.activeElement!==$('timeSlider'))$('timeSlider').value=M.clamp(state.time,state.collection?-259200:-36000,state.collection?259200:36000);$('performance').textContent=canvas.width+' × '+canvas.height+' · '+(state.playing||keys.size?'LIVE':'IDLE');}
 function frame(now){requestAnimationFrame(frame);const elapsed=(now-last)/1000,dt=Math.min(.05,elapsed);last=now;if(document.hidden||capturing||window.spherePreviewSuspended)return;
  if(state.playing){state.time+=elapsed*state.timeRate;if(Math.abs(state.time)>1e9){state.playing=false;sync();toast('Time limit reached. Reset the shade pass.');}dirty=true;}
  if(keys.size){const b=M.basis(state.forward,state.up);let move=[0,0,0];for(const [key,vec] of [['KeyW',b.f],['KeyS',M.mul(b.f,-1)],['KeyD',b.r],['KeyA',M.mul(b.r,-1)],['KeyE',b.u],['KeyQ',M.mul(b.u,-1)]])if(keys.has(key))move=M.add(move,vec);
   if(M.length(move)>0){let step=state.speed*dt*(keys.has('ShiftLeft')||keys.has('ShiftRight')?5:1);const dir=M.norm(move),hit=M.sphereDistance(state.position,dir,[0,0,0],state.starRadius*1.02);if(hit<step)step=Math.max(0,hit-1);let p=M.add(state.position,M.mul(dir,step));const r=M.length(p);if(r>=state.radius-1)p=M.mul(M.norm(p),state.radius-1);if(r<=state.starRadius*1.02)p=M.mul(M.norm(p),state.starRadius*1.02);state.position=p;moved();dirty=true;}
  }
  if(dirty&&now-lastPreviewDraw>=1000/previewFps){const rect=viewport.getBoundingClientRect(),requested=Math.min(devicePixelRatio||1,1.5)*state.quality,scale=Math.min(requested,Math.sqrt(1920*1080/Math.max(1,rect.width*rect.height)));const w=Math.max(1,Math.floor(rect.width*scale)),h=Math.max(1,Math.floor(rect.height*scale));const start=performance.now();renderer.draw(state,w,h);lastPreviewDraw=now;renderCost=performance.now()-start;dirty=false;}
  if(now-hudTime>250){hudTime=now;hud();}
 }
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('error').hidden=false;$('error').textContent='The graphics context was interrupted. Reload this page to restore the renderer. Exported scenes and saved viewpoints are safe.';state.playing=false;});
 // Diagnostics used by local verification. No network or remote control interface.
 window.SphereApp={getState:()=>structuredClone(state),setState:s=>{state=M.validate(s);state.playing=s.playing===true;sync();},preset,renderer,draw:()=>{dirty=true;},setBusy:v=>{capturing=v;keys.clear();dirty=true;last=performance.now();},capture,record,assumptions,toast,download,get renderCost(){return renderCost;}};
 sync();showBookmarks();if(innerWidth<760)document.body.classList.add('panel-hidden');requestAnimationFrame(frame);
})();
