(function(){
 'use strict';const M=SphereMath,$=id=>document.getElementById(id);
 let lastPreviewDraw=-Infinity,previewFps=60,frameCount=0,fpsStart=performance.now(),measuredFps=0;
 let state=M.defaultState(),renderer,dirty=true,capturing=!!$('sceneLoading'),last=performance.now(),hudTime=0,renderCost=0,toastTimer,keys=new Set(),drag=null,verticalFlight=null;
 const viewport=$('viewport'),canvas=$('view'),previewQuality=new SpherePreviewQuality();
 let travelHold=false;
 function navigationIntent(){window.dispatchEvent(new Event('sphere-user-navigation-intent'));}
 try{const saved=Number(localStorage.getItem('sphere-preview-fps'));if([15,30,60].includes(saved))previewFps=saved;}catch{}
 $('previewFps').value=String(previewFps);$('previewFps').onchange=()=>{previewFps=Number($('previewFps').value);try{localStorage.setItem('sphere-preview-fps',String(previewFps));}catch{}dirty=true;};
 try{renderer=new SphereRenderer(canvas);}catch(e){$('error').hidden=false;$('error').textContent=e.message;return;}
 const actions=document.querySelector('.view-actions'),tools=document.createElement('div'),keyboardMap=document.createElement('div');tools.className='view-tools';keyboardMap.className='keyboard-map';keyboardMap.setAttribute('aria-label','Keyboard controls');keyboardMap.innerHTML='<span class="keyboard-map-title">FLIGHT CONTROLS</span><div><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd><span>fly</span></div><div><kbd>Q</kbd><kbd>E</kbd><span>down / up</span><kbd>Z</kbd><kbd>X</kbd><span>turn</span></div><small>Shift · fast&nbsp;&nbsp; Space · shades</small>';actions.replaceWith(tools);tools.append(actions,keyboardMap);const controlStyle=document.createElement('style');controlStyle.textContent='.view-tools{display:flex;flex-direction:column;align-items:flex-end;gap:8px}.keyboard-map{padding:8px 10px;border:1px solid #ffffff22;border-radius:3px;background:#10182055;color:#e7e9e7;font-size:9px;line-height:1.8;letter-spacing:.2px;text-align:right;text-shadow:0 1px 8px #000;pointer-events:none;white-space:nowrap}.keyboard-map-title{display:block;color:#aeb9b8;font-size:8px;letter-spacing:1.4px;margin-bottom:2px}.keyboard-map kbd{display:inline-flex;align-items:center;justify-content:center;min-width:15px;height:15px;margin-left:3px;border:1px solid #ffffff55;border-radius:2px;background:#ffffff0b;color:#f0f2ef;font:9px/1 monospace}.keyboard-map span:not(.keyboard-map-title){margin-left:5px;color:#c8d0ce}.keyboard-map small{display:block;color:#aeb9b8;font-size:8px}.view-top{align-items:flex-start}@media(max-width:760px){.keyboard-map{font-size:8px;padding:6px 8px}.keyboard-map kbd{min-width:13px;height:13px;font-size:8px}}';document.head.append(controlStyle);
 function clearFlightKeys(){keys.clear();verticalFlight=null;}
 function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),4500);}
 const distance=v=>!Number.isFinite(v)?'Beyond the shell':Math.abs(v)<1?(v*1000).toLocaleString(undefined,{maximumFractionDigits:1})+' m':v>=1e6?(v/1e6).toFixed(3)+' million km':v.toLocaleString(undefined,{maximumFractionDigits:1})+' km';
 const timeLabel=v=>{const sign=v<0?'−':'',s=Math.floor(Math.abs(v));return sign+[Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(x=>String(x).padStart(2,'0')).join(':');};
 const transforms={radius:1e6,breachDiameter:1e6};
 const fields=['radius','starRadius','luminosity','breachEnabled','breachDiameter','breachLat','breachLon','breachRoughness','surfaceStyle','shadeEnabled','shadeAltitude','shadeDiameter','shadeOffset','shadeDamage','shadeSpeed','shellshine','atmosphere','seed','starfield','fov','speed','projection','viewMode','grid','exposure','timeRate','quality'];
 function updateOutput(){$('starScale').textContent=new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(state.starRadius)+' km radius = '+new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(state.starRadius*2)+' km across';for(const k of ['fov','exposure','shellshine','atmosphere','shadeOffset','shadeDamage','breachRoughness']){const el=$(k+'Value');if(!el)continue;el.textContent=k==='fov'?state.fov+'°':k==='exposure'?state.exposure.toFixed(1)+' stops':k==='shadeOffset'?state.shadeOffset.toFixed(2)+' radii':Math.round(state[k]*100)+'%';}}
 function syncCameraFields(){const ll=M.latlon(state.position);$('cameraLat').value=ll[0].toFixed(5);$('cameraLon').value=ll[1].toFixed(5);$('cameraAltitude').value=(state.radius-M.length(state.position)).toFixed(3);$('cameraAltitude').max=state.layoutVersion===2?state.radius:state.radius-state.starRadius*1.02;}
 function sync(){for(const k of fields){const el=$(k);if(el.type==='checkbox')el.checked=state[k];else {const value=String(state[k]/(transforms[k]||1));if(el.tagName==='SELECT'){const str=typeof state[k]==='string'?state[k]:value;if(![...el.options].some(o=>o.value===str)){const op=document.createElement('option');op.value=str;op.textContent=str+' · custom';el.append(op);}el.value=str;}else el.value=value;}}
  syncCameraFields();updateOutput();$('timeSlider').value=M.clamp(state.time,state.collection?-259200:-36000,state.collection?259200:36000);$('play').textContent=state.playing?'Ⅱ':'▶';$('stateIndicator').textContent=state.playing?'RUNNING':'PAUSED';$('wholeArea').textContent=(state.radius/M.AU).toFixed(3)+' AU radius';document.querySelector('.panel-foot span').textContent=(Math.pow(state.radius/6371,2)/1e6).toFixed(1)+' million Earth surfaces';dirty=true;hudTime=0;window.dispatchEvent(new Event('sphere-state-synced'));
 }
 function chooseTab(name){document.querySelectorAll('[data-tab]').forEach(el=>{el.classList.toggle('active',el.dataset.tab===name);el.setAttribute('aria-selected',String(el.dataset.tab===name));});document.querySelectorAll('.tab-panel').forEach(el=>el.hidden=el.id!==name);if(name==='camera')syncCameraFields();}
 document.querySelectorAll('[data-tab]').forEach(el=>el.addEventListener('click',()=>chooseTab(el.dataset.tab)));
 for(const k of fields){const el=$(k);el.addEventListener(el.type==='range'?'input':'change',()=>{
  const before=structuredClone(state);let value=el.type==='checkbox'?el.checked:el.tagName==='SELECT'&&['projection','viewMode','surfaceStyle'].includes(k)?el.value:Number(el.value)*(transforms[k]||1);
  state[k]=value;if(k==='speed')state.autoSpeed=false;
  if(k==='radius')state.position=M.mul(before.position,value/before.radius);
  try {const wasPlaying=state.playing;state=M.validate(state);state.playing=wasPlaying;}
  catch(e){state=before;sync();toast(e.message);return;}
  updateOutput();dirty=true;window.dispatchEvent(new Event('sphere-world-changed'));if(k==='radius'||k==='speed')sync();if(k==='projection')toast(value==='panorama'?'360° panorama: poles stretch in this flat projection.':'Photographic perspective restored.');
 });}
 document.querySelectorAll('summary .toggle').forEach(el=>el.addEventListener('click',e=>e.stopPropagation()));
 function setLook(f,up=[0,1,0]){const b=M.basis(f,up);state.forward=b.f;state.up=b.u;dirty=true;}
 function autoLevelIfNearSurface(){const changed=SphereInspection.level(state,1000);dirty=dirty||changed;return changed;}
 let integratingMovement=false,poseChanged=false;
 function moved(){if(integratingMovement){poseChanged=true;return;}const location=window.SphereJourney?.current();if(location)$('viewTitle').textContent=location.title;window.dispatchEvent(new Event('sphere-pose-updated'));window.dispatchEvent(new Event('sphere-view-changed'));}
 function buildPreset(input,name,{stage=false}={}){const next=stage?M.defaultState():structuredClone(input),look=(f,up=[0,1,0])=>Object.assign(next,{forward:M.basis(f,up).f,up:M.basis(f,up).u});
  Object.assign(next,{walkMode:false,walkSurface:false,walkPosition:null,siteId:'',siteAnchor:null,shadeAttachment:null});
  if(name==='interior'){next.position=[0,0,next.radius*.5];look([0,0,1]);next.fov=105;}
  if(name==='breach'){const n=M.axis(next.breachLat,next.breachLon);next.position=M.mul(n,next.radius*.60);look(n);next.fov=100;next.speed=100000;}
  if(name==='shade'){next.position=[0,0,next.radius-300];next.shadeOffset=0;look([-.65,0,-1]);next.fov=95;next.speed=1000;next.exposure=.7;}
  if(name==='dawn'){next.position=[0,0,next.radius-1];next.shadeOffset=1;look([.24,.07,-1]);next.fov=100;next.atmosphere=1;next.exposure=.2;next.speed=10;}
  if(!stage){const pose={position:next.position,forward:next.forward,up:next.up,walkMode:false,walkSurface:false,walkPosition:null,siteId:'',siteAnchor:null,shadeAttachment:null};Object.assign(next,input,pose);}else for(const k of ['antialias','shadowSamples','stationSamples','quality'])next[k]=input[k];return next;
 }
 function preset(name,{stage=false}={}){return SphereJourney.travel.request({type:stage?'saved':'place',title:({interior:'The interior',breach:'The breach',shade:'Under the shade',dawn:'First light'})[name],resolve:s=>buildPreset(s,name,{stage})});}
 document.querySelectorAll('[data-preset]').forEach(el=>el.addEventListener('click',()=>preset(el.dataset.preset)));
 document.querySelectorAll('[data-turn]').forEach(el=>el.onclick=()=>{if(capturing)return;const b=M.basis(state.forward,state.up),axis=el.dataset.turn==='yaw'?b.u:el.dataset.turn==='pitch'?b.r:b.f,angle=M.radians(Number($('rotationStep').value))*Number(el.dataset.sign);setLook(M.rotate(b.f,axis,angle),M.rotate(b.u,axis,angle));moved();});
 $('levelCamera').onclick=()=>{if(capturing)return;const up=SphereInspection.surface(state).up;if(Math.abs(M.dot(up,state.forward))>.999){toast('Looking almost straight up or down: use Roll to choose an orientation.');return;}setLook(state.forward,up);moved();};
 $('faceSurface').onclick=()=>{setLook(M.norm(state.position));moved();};$('faceStar').onclick=()=>{setLook(M.mul(M.norm(state.position),-1));moved();};
 $('inspectBelow').onclick=()=>{setLook(M.norm(state.position));moved();toast('Looking toward the nearby surface. Detail follows the distance to what you see.');};
 $('moveCamera').onclick=()=>{const lat=Number($('cameraLat').value),lon=Number($('cameraLon').value),alt=Number($('cameraAltitude').value);if(![lat,lon,alt].every(Number.isFinite)||Math.abs(lat)>90||Math.abs(lon)>180||alt<.001||alt>state.radius){toast('Choose valid latitude, longitude and altitude inside the shell.');return;}SphereJourney.travel.request({type:'place',title:'Exact shell address',resolve:input=>({...input,position:M.mul(M.axis(lat,lon),input.radius-alt),walkMode:false,walkSurface:false,walkPosition:null,siteId:'',siteAnchor:null,shadeAttachment:null})});};
 function setPlaying(value){state.playing=!!value;sync();}
 $('play').onclick=()=>setPlaying(!state.playing);$('resetTime').onclick=()=>{SphereInspection.setTime(state,0);sync();};
 $('timeSlider').oninput=e=>{SphereInspection.setTime(state,Number(e.target.value));sync();};
 $('togglePanel').onclick=()=>{document.body.classList.toggle('panel-hidden');dirty=true;};
 $('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await viewport.requestFullscreen();}catch{toast('This browser did not allow full-screen mode.');}dirty=true;};
 $('helpButton').onclick=()=>{clearFlightKeys();$('guide').showModal();};$('closeGuide').onclick=()=>$('guide').close();
 viewport.addEventListener('pointerdown',e=>{if(e.target!==canvas)return;viewport.focus({preventScroll:true});drag={x:e.clientX,y:e.clientY,id:e.pointerId};canvas.setPointerCapture(e.pointerId);});
 canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;if(dx||dy)navigationIntent();if(travelHold)return;const b=M.basis(state.forward,state.up),yaw=-dx*.003,pitch=-dy*.003;let f=M.rotate(b.f,b.u,yaw),r=M.norm(M.cross(f,b.u));f=M.rotate(f,r,pitch);state.up=M.norm(M.rotate(b.u,r,pitch));state.forward=M.norm(f);moved();dirty=true;});
 canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('lostpointercapture',()=>drag=null);
 viewport.addEventListener('wheel',e=>{if(e.target!==canvas)return;e.preventDefault();state.autoSpeed=false;state.speed=M.clamp(state.speed*Math.exp(-e.deltaY*.0015),state.layoutVersion===2?.001:1,3e7);sync();},{passive:false});
 function takeoff(){if(SphereTravel.takeoff(state)){verticalFlight=SphereInspection.surface(state).up;keys.delete('Space');dirty=true;sync();$('viewTitle').textContent='Lifting off';toast('Lifting off. E climbs; W flies forward.');return true;}return false;}
 window.addEventListener('keydown',e=>{if($('guide').open||/INPUT|SELECT|TEXTAREA|BUTTON/.test(e.target.tagName))return;
  if(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','KeyZ','KeyX'].includes(e.code)||(e.code==='Space'&&state.walkMode)){navigationIntent();if(travelHold)return;}
  if((e.code==='KeyE'||e.code==='KeyQ')&&!keys.has('KeyE')&&!keys.has('KeyQ')){const axis=SphereInspection.surface(state).up;verticalFlight=M.length(axis)>.5?axis:state.up.slice();}
  if(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','KeyZ','KeyX','ShiftLeft','ShiftRight','Space'].includes(e.code)){keys.add(e.code);e.preventDefault();}
  if((e.code==='KeyE'||e.code==='Space')&&keys.has('KeyE')&&keys.has('Space')){takeoff();return;}
  if(e.code==='KeyH')document.body.classList.toggle('clean');
  if(e.code==='Space'&&!state.walkMode&&!SphereTravel.lifting&&!e.repeat)setPlaying(!state.playing);
 });
 window.addEventListener('keyup',e=>{keys.delete(e.code);if(!keys.has('KeyE')&&!keys.has('KeyQ'))verticalFlight=null;});window.addEventListener('blur',()=>{clearFlightKeys();drag=null;});document.addEventListener('visibilitychange',()=>{clearFlightKeys();last=performance.now();dirty=true;});
 new ResizeObserver(()=>dirty=true).observe(viewport);
 window.addEventListener('sphere-light-ready',()=>dirty=true);window.addEventListener('sphere-texture-ready',()=>dirty=true);window.addEventListener('pagehide',()=>renderer.dispose());
 let bookmarks=[];try{const stored=JSON.parse(localStorage.getItem('sphere-bookmarks-v1')||'[]');if(Array.isArray(stored))bookmarks=stored.filter(x=>typeof x.name==='string'&&x.state).slice(0,50);}catch{}
 function storeBookmarks(){try{localStorage.setItem('sphere-bookmarks-v1',JSON.stringify(bookmarks));}catch{toast('Browser storage is unavailable. Export a scene file to keep this view.');}}
 function showBookmarks(){const box=$('bookmarks');box.replaceChildren();for(let i=0;i<bookmarks.length;i++){const row=document.createElement('div');row.className='bookmark-row';const go=document.createElement('button');go.className='secondary';go.textContent=bookmarks[i].name;go.onclick=()=>SphereJourney.visit(bookmarks[i].state,bookmarks[i].name);const del=document.createElement('button');del.className='quiet';del.textContent='×';del.setAttribute('aria-label','Delete '+bookmarks[i].name);del.onclick=()=>{bookmarks.splice(i,1);storeBookmarks();showBookmarks();};row.append(go,del);box.append(row);}}
 $('saveBookmark').onclick=()=>{const name=$('bookmarkName').value.trim()||$('viewTitle').textContent;if(bookmarks.length>=50){toast('You have 50 viewpoints. Export some scenes or remove an old viewpoint.');return;}bookmarks.push({name,state:structuredClone(state)});storeBookmarks();showBookmarks();toast('Viewpoint saved in this browser.');};
 function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
 const assumptions={collection:'Optional Collection study v1: three prescribed shade routes, 18 intact/12 surviving shades with selectable planar disk, square, curved spherical-cap or trimmed-cap geometry, six analytic elliptical wounds, two stellar-service rings. Layout is provisional. ShellShine uses 192 equal-area samples of macro albedo and direct light, one diffuse bounce with adjustable strength. Direct occlusion uses seven or nineteen shared stellar samples without the station, or a selectable 19/64/128/256 common sample set with the station enabled, with receiver self-exclusion. Trimmed caps have planar side cuts parallel to travel; the width is adjustable. On supported GPUs, linear half-float radiance is filtered before exposure and SDR tone mapping. Unsupported GPUs retain display-colour supersampling. In the designed layout, Smooth edges integrates eight subpixel primary rays near analytic Shade boundaries before the local geometry and volume passes. Other pixels keep their centre ray; geometric depth also remains centre sampled. An optional contrast-directed display filter can soften fine detail. Construction texture pitches are fixed in kilometres and filtered with footprint. Surface detail, haze, shade penumbrae and damage are approximate. No mirror delivery, concealment, ablation, orbital evolution or light travel time is simulated.',geometry:'Analytic inner sphere and star; spherical-cap breach with optional defined fractured edge; thin planar shade with optional circular notch. CPU double precision; normalized GPU highp float with stable near-shell root and camera-relative shade coordinates.',lighting:'Direct stellar illumination with sampled shade penumbra. Original studies use uniform fill; Collection study uses a sampled macro-albedo first-bounce estimate with user strength. Approximate local atmospheric scattering only. No solved global multiple scattering or calibrated photometry.',surface:'Three finite generated biome texture tiers (256 / 16 / 1 km tiles), blended by visible surface distance near 1000 / 100 / 10 km with footprint filtering. Deterministic regional atlas with filtered, world-anchored detail bands (or legacy albedo) on a smooth shell; no local relief, populated worlds or detailed terrain.',dynamics:'Free camera; prescribed straight shade pass. Artificial gravity, support, containment and propulsion assumed. No orbit, climate or material-strength model.',stars:'External stars are illustrative and fixed, not an astronomical catalogue.'};
 function record(extra={}){return M.sceneRecord(state,{application:'The Sphere Observatory '+(window.SphereBuild?.version||'1.6.0'),build:window.SphereBuild||{status:'unverified local build'},location:window.SphereJourney?.current(),title:$('captureTitle')?.value||$('viewTitle').textContent,units:'kilometres, seconds, degrees; luminosity in solar units',assumptions,...extra});}
 $('saveScene').onclick=()=>download(new Blob([JSON.stringify(record(),null,2)],{type:'application/json'}),'sphere-scene.json');
 $('loadScene').onclick=()=>$('sceneFile').click();$('sceneFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>1000000)throw Error('Scene files must be smaller than 1 MB.');const parsed=JSON.parse(await file.text());if(parsed.format!=='sphere-observatory'||parsed.version!==1)throw Error('This file is not a supported Sphere scene.');const imported=M.validate(parsed.state);await SphereJourney.visit(imported,parsed.location?.title||'Imported viewpoint');}catch(err){toast('Could not import: '+err.message);}finally{e.target.value='';}};
 let captureController=null;
 const captureStatus=(phase,message)=>window.dispatchEvent(new CustomEvent('sphere-capture-status',{detail:{state:phase,message}}));
 async function capture({projection}={}){if(capturing||travelHold){toast('Finish the current travel or capture first.');return;}capturing=true;captureController=new AbortController();const signal=captureController.signal,button=$('capture');button.disabled=true;clearFlightKeys();const snapshot=structuredClone(state);snapshot.playing=false;if(projection)snapshot.projection=projection;const width=Number($('exportSize').value),height=Math.round(width/(snapshot.projection==='panorama'?2:16/9)),identity=window.SphereJourney?.current(),title=$('captureTitle')?.value||identity?.title;
  captureStatus('preparing','Preparing complete frame…');const check=()=>{if(signal.aborted)throw new DOMException('Capture cancelled.','AbortError');};
  try{await new Promise(resolve=>requestAnimationFrame(resolve));check();if(width>renderer.gl.getParameter(renderer.gl.MAX_RENDERBUFFER_SIZE))throw Error('That resolution is above this GPU’s limit. Choose a smaller photograph.');await renderer.prepare(snapshot,{aspect:width/height,signal});check();
   renderer.draw(snapshot,width,height,{exportFrame:true});renderer.draw(snapshot,width,height,{exportFrame:true});check();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));check();if(!blob)throw Error('The browser could not encode the image.');const bytes=new Uint8Array(await blob.arrayBuffer());check();
   const meta=M.sceneRecord(snapshot,{application:'The Sphere Observatory '+(window.SphereBuild?.version||'1.6.0'),build:window.SphereBuild||{status:'unverified local build'},location:identity,title,units:'km, seconds, degrees',image:{width,height,render:renderer.renderInfo,projection:snapshot.projection,horizontalFieldOfView:snapshot.projection==='panorama'?360:snapshot.fov},readiness:'complete-frame preparation; cold repeatability remains under verification',assumptions});
   const enc=new TextEncoder();download(SphereZip([['photograph.png',bytes],['scene.json',enc.encode(JSON.stringify(meta,null,2))],['READ-ME.txt',enc.encode('The Sphere Observatory\nImport scene.json to restore this photograph. Geometry and lighting are approximations; see scene metadata.\n')]]),'sphere-photograph-'+new Date().toISOString().replace(/[:.]/g,'-')+'.zip');captureStatus('complete','Photograph and scene exported.');
  }catch(e){const cancelled=signal.aborted||e.name==='AbortError',message=cancelled?'Capture cancelled.':e.message;captureStatus(cancelled?'cancelled':'failed',message);toast(message);}finally{captureController=null;capturing=false;button.disabled=false;dirty=true;last=performance.now();}
 }
 $('capture').onclick=capture;
 function hud(){const fpsNow=performance.now();if(fpsNow-fpsStart>=1000){measuredFps=frameCount*1000/(fpsNow-fpsStart);frameCount=0;fpsStart=fpsNow;}const starAngle=2*M.degrees(Math.asin(M.clamp(state.starRadius/M.length(state.position),0,1))),target=window.SphereSites?SphereSites.trace(state.position,state.forward,state,M.trace):M.trace(state.position,state.forward,state);const attached=SphereInspection.plate(state),ground=SphereInspection.surface(state);$('altitudeReadout').textContent=distance(attached?ground.altitude:SphereLanding.heightAboveGround(state));$('altitudeReadout').previousElementSibling.textContent=attached?'ALTITUDE · SHADE '+attached.id:'ALTITUDE';$('altitudeReadout').title=attached?'Distance above the inspected Shade; '+distance(state.radius-M.length(state.position))+' above the shell':'';$('starReadout').textContent=starAngle.toFixed(4)+'°';$('sunReadout').textContent=Math.round(M.sunVisibility(state.position,state,256)*100)+'%';$('speedReadout').textContent=state.walkMode?(keys.has('ShiftLeft')||keys.has('ShiftRight')?'6 m/s · run':'2.8 m/s · walk'):distance(state.autoSpeed===false?state.speed:(SphereTravel.estimate(state,state.forward)))+'/s'+(state.autoSpeed===false?'':' · auto');$('targetName').textContent=target.kind;$('targetDistance').textContent=distance(target.distance);$('timeReadout').textContent=timeLabel(state.time);window.dispatchEvent(new Event('sphere-telemetry'));if(document.activeElement!==$('timeSlider'))$('timeSlider').value=M.clamp(state.time,state.collection?-259200:-36000,state.collection?259200:36000);$('performance').textContent=canvas.width+' × '+canvas.height+' · '+(state.playing||keys.size?'LIVE':'IDLE')+(state.playing||keys.size?' '+Math.round(measuredFps)+' fps':'')+' · CPU '+(renderer.cpuMs||0).toFixed(1)+' ms'+(renderer.gpuMs!==null?' · GPU '+renderer.gpuMs.toFixed(1)+' ms':'')+(previewQuality.scale<1&&(state.playing||keys.size)?' · adaptive '+Math.round(previewQuality.scale*100)+'%':'');$('performance').title=renderer.device;}
 function frame(now){requestAnimationFrame(frame);const elapsed=(now-last)/1000,dt=Math.min(.05,elapsed);last=now;if(document.hidden||capturing||travelHold||window.spherePreviewSuspended)return;
  integratingMovement=true;
  SphereTiming.advance(state,elapsed,dt=>{if(state.playing)dirty=true;
  if(window.SphereEnhancements?.measuring){}
  else if(SphereTravel.stepTakeoff(state,dt)){dirty=true;}
  else if(state.walkMode){if(SphereSites.step(state,keys,dt)){dirty=true;moved();}}
  else if(keys.size){const b=M.basis(state.forward,state.up),vertical=verticalFlight||SphereInspection.surface(state).up;let move=[0,0,0];for(const [key,vec] of [['KeyW',b.f],['KeyS',M.mul(b.f,-1)],['KeyD',b.r],['KeyA',M.mul(b.r,-1)],['KeyE',vertical],['KeyQ',M.mul(vertical,-1)]])if(keys.has(key))move=M.add(move,vec);
   const turn=(keys.has('KeyZ')?1:0)+(keys.has('KeyX')?-1:0);if(turn){const angle=turn*dt*M.radians(45);setLook(M.rotate(b.f,b.u,angle),M.rotate(b.u,b.u,angle));moved();}
   if(M.length(move)>0){const dir=M.norm(move);let step=SphereTravel.speed(state,dir,dt,keys.has('ShiftLeft')||keys.has('ShiftRight'))*dt;if(state.layoutVersion!==2){const star=M.sphereDistance(state.position,dir,[0,0,0],state.starRadius*1.02);if(star<step)step=Math.max(0,star-1);}const travel=window.SphereLanding?SphereLanding.move(state,dir,step):window.SphereFlight?SphereFlight.move(state,dir,step):{position:M.add(state.position,M.mul(dir,step))};let p=travel.position;const r=M.length(p);const limit=state.layoutVersion===2?state.radius*1.999:state.radius-1;if(r>=limit)p=M.mul(M.norm(p),limit);if(state.layoutVersion!==2&&r<=state.starRadius*1.02)p=M.mul(M.norm(p),state.starRadius*1.02);const crossed=state.radius-M.length(state.position)>1000&&state.radius-r<=1000;state.position=p;if(crossed&&state.autoSpeed===false)autoLevelIfNearSurface();moved();if(travel.landed){sync();$('viewTitle').textContent='Arriving on foot';toast('Landing here. Drag to look; W A S D to walk, Shift to run, Space to jump.');}dirty=true;}
  }
  if(!window.SphereEnhancements?.measuring&&(state.autoSpeed===false?SphereInspection.level(state):SphereTravel.level(state,dt)))dirty=true;
  });
  integratingMovement=false;if(poseChanged){poseChanged=false;moved();}
  if((dirty||renderer.needsFrame)&&window.SphereLoading?.needs(state)){SphereLoading.ensureCurrent();return;}
  if((dirty||renderer.needsFrame)&&(now-lastPreviewDraw>=1000/previewFps-.8)){const rect=viewport.getBoundingClientRect(),requested=Math.min(devicePixelRatio||1,1.5)*state.quality,live=state.playing||keys.size||drag,adaptive=$('adaptivePreview')?.checked!==false&&live?previewQuality.update(renderer.gpuMs,1000/previewFps,now):1,scale=Math.min(requested*adaptive,Math.sqrt(3840*2160/Math.max(1,rect.width*rect.height)));const w=Math.max(1,Math.floor(rect.width*scale)),h=Math.max(1,Math.floor(rect.height*scale));const start=performance.now();renderer.draw(state,w,h,{adaptiveScale:adaptive});frameCount++;lastPreviewDraw=SphereTiming.previewStamp(lastPreviewDraw,now,previewFps);renderCost=performance.now()-start;dirty=false;}
  if(now-hudTime>250){hudTime=now;hud();}
 }
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('error').hidden=false;$('error').textContent='The graphics context was interrupted. Reload this page to restore the renderer. Exported scenes and saved viewpoints are safe.';capturing=true;clearFlightKeys();});
 // Diagnostics used by local verification. No network or remote control interface.
 window.SphereApp={get travelHeld(){return travelHold;},setTravelHold:v=>{travelHold=v;clearFlightKeys();dirty=true;last=performance.now();},commitTravel:(next,candidate)=>{const clean=M.validate(next);clean.playing=state.playing;SphereLanding.activate(candidate);SphereTravel.reset();verticalFlight=null;state=clean;sync();},get busy(){return capturing;},getState:()=>structuredClone(state),takeoff,setPlaying,setState:s=>{const next=M.validate(s);next.playing=state.playing;
  const samePose=['position','forward','up'].every(k=>Array.isArray(s[k])&&s[k].every((v,i)=>v===state[k][i]));
  if(next.shadeAttachment!==null&&next.shadeAttachment===state.shadeAttachment&&samePose)SphereInspection.transport(state,next);
  if(!samePose){SphereTravel.reset();verticalFlight=null;}state=next;SphereInspection.level(state);sync();},preset,buildPreset,autoLevelIfNearSurface,renderer,draw:()=>{dirty=true;},setBusy:(v,{keepKeys=false}={})=>{capturing=v;if(!keepKeys)clearFlightKeys();dirty=true;last=performance.now();},capture,cancelCapture:()=>captureController?.abort(),record,assumptions,toast,download,get renderCost(){return renderCost;}};
 sync();showBookmarks();if(innerWidth<760)document.body.classList.add('panel-hidden');requestAnimationFrame(frame);
})();
