/* Version-two world controls and bounded field expeditions. */
(function(){
'use strict';const A=SphereApp,M=SphereMath,W=SphereWorld,S=SphereSites,B=SphereBiomes,$=id=>document.getElementById(id);
let returnState=null;
function changed(s,title){A.setState(s);$('viewTitle').textContent=title;window.dispatchEvent(new Event('sphere-view-changed'));$('viewport').focus({preventScroll:true});}
function visit(id,{walk=false,altitude=.25}={}){const s=A.getState(),inheritedExposure=/^(rim|exterior-)/.test(s.siteId)?(returnState?.exposure??-.15):s.exposure;returnState=returnState||structuredClone(s);s.exposure=inheritedExposure;s.layoutVersion=2;s.collection=true;s.siteId=id;s.shadeAttachment=null;s.walkMode=false;s.walkPosition=null;s.biome=-1;s.geometryDetail=true;s.projection='perspective';s.fov=78;s.speed=.02;s.playing=false;let title;
 if(id.startsWith('biome-')){const biome=Number(id.slice(6));if(biome===4&&s.era==='before'){A.toast('The Ruin is a post-attack landscape. Choose After attack to walk it.');return;}const q=W.locateBiome(biome,s);s.siteAnchor=q;s.position=M.mul(q,s.radius-altitude);const frame=S.shellFrame(q);s.forward=M.norm(M.add(frame[2],M.mul(frame[1],-.40)));s.up=frame[1];title=B.catalog[biome].name+' · field site';if(walk)S.enterWalk(s);}
 else if(id==='rim'){s.era='after';s.multipleWounds=true;const f=W.rimFrame(s),q=M.norm(M.add(f.point,M.mul(f.inland,-8/s.radius)));s.siteAnchor=q;s.position=M.mul(q,s.radius-5.0);s.forward=M.norm(M.add(M.add(f.inland,M.mul(f.tangent,.70)),M.mul(f.point,.65)));s.up=M.mul(q,-1);s.fov=86;s.exposure=1.6;title='Wound · exposed shell edge';}
 else if(id.startsWith('port-')){const q=M.mul(W.frame(s).axis,id.endsWith('0')?1:-1),frame=S.shellFrame(q);s.siteAnchor=q;s.position=M.mul(q,s.radius-.23);s.forward=M.norm(M.add(frame[2],M.mul(frame[1],-.7)));s.up=frame[1];title='Polar entry '+(id.endsWith('0')?'A':'B')+' · service court';if(walk)S.enterWalk(s);}
 else if(id.startsWith('shade-')){s.routeShades=true;const plates=SphereCollection.plates(s),wanted=Number(id.slice(6));if(!plates.some(p=>p.id===wanted)){A.toast('That Shade does not survive in this era.');return;}s.shadeAttachment=wanted;s.siteAnchor=plates.find(p=>p.id===wanted).normal;const mesh=S.shadeSection(s);s.position=mesh.world([-.3,.20,.75]);s.forward=M.norm(M.sub(mesh.world([.5,-.04,0]),s.position));s.up=mesh.basis[1];title='Shade '+wanted+' · '+(s.era==='after'?'fracture inspection':'service skin');}
 else if(id.startsWith('exterior-')){s.era='after';s.wreckage=true;s.spaceEnvironment=Number(id.slice(9));const rim=W.rimFrame(s);s.siteAnchor=M.norm(M.add(rim.point,M.mul(rim.inland,-30000/s.radius)));const mesh=S.exterior(s);s.position=mesh.world([0,0,-4]);s.forward=M.norm(M.add(mesh.basis[2],M.mul(mesh.basis[1],-.25)));s.up=mesh.basis[1];s.speed=10;s.exposure=1.5;title=['Breach spill','Ancient graveyard','Contested approach'][s.spaceEnvironment];}
 else throw Error('Unknown destination');
 changed(s,title+(s.walkMode?' · on foot':''));sync();return s;
}
function restore(){if(!returnState)return;const saved=returnState;returnState=null;changed(saved,'Previous view');sync();}
const geography=document.createElement('details');geography.open=true;geography.className='world-geography';geography.innerHTML=`<summary>Shell geography</summary>
<label class="field">Surface arrangement<select id="layoutVersion"><option value="2">Designed waist and machinery fields</option><option value="1">Legacy · intersecting belts</option></select></label>
<p class="micro">Three habitat ribbons share one waist. Thermal routing, air and water works, and fabrication districts support them. Two entry facilities occupy opposite poles. The Shade routes follow the three ribbons and rotate with this axis.</p>
<div class="two"><label class="field">Axis latitude<span>°</span><input id="axisLat" type="number" min="-90" max="90" step="1"></label><label class="field">Axis longitude<span>°</span><input id="axisLon" type="number" min="-180" max="180" step="1"></label></div>
<label class="field">Habitat half-width<span>°</span><input id="waistWidth" type="range" min="10" max="38" step="1"></label>
<label class="field">Transition width<span>km</span><input id="transitionKm" type="number" min="100" max="500000" step="1000"></label>
<label class="field">Exposed shell thickness<span>km · provisional</span><input id="shellThickness" type="number" min="0.1" max="1000" step="1"></label>
<label class="check"><input id="geometryDetail" type="checkbox"> Local terrain, structures and Wound edges</label>
<label class="check"><input id="wreckage" type="checkbox"> Post-attack exterior wreckage</label>
<label class="field">Exterior environment<select id="spaceEnvironment"><option value="0">Breach spill</option><option value="1">Ancient graveyard</option><option value="2">Contested approach</option></select></label>
<p id="worldLocation" class="micro"></p>`;
$('scene').prepend(geography);
const journeys=document.createElement('details');journeys.open=true;journeys.id='fieldExpeditions';journeys.innerHTML=`<summary>Field expeditions</summary>
<label class="field">Local destination<select id="fieldDestination">${B.catalog.map((b,i)=>`<option value="biome-${i}">${b.name}</option>`).join('')}<option value="rim">Wound edge</option><option value="port-0">Polar entry A</option><option value="port-1">Polar entry B</option><option value="shade-0">Shade · radial fracture</option><option value="shade-7">Shade · sheared section</option><option value="shade-8">Shade · diagonal break</option><option value="exterior-0">Exterior · breach spill</option><option value="exterior-1">Exterior · ancient graveyard</option><option value="exterior-2">Exterior · contested approach</option></select></label>
<div class="two"><button id="visitField" class="secondary">Inspect site</button><button id="walkField" class="secondary">Walk here</button></div><button id="returnField" class="quiet full">Return to previous view</button>
<p id="fieldStatus" class="micro">Walkable samples span 2.4 km. W A S D moves, Shift runs, Space jumps; drag to look. Obstacles and ground use the rendered geometry.</p>`;
$('camera').prepend(journeys);
const weather=document.createElement('details');weather.open=true;weather.innerHTML=`<summary>Local weather</summary><label class="check"><input id="clouds" type="checkbox"> Clouds and suspended particles</label><label class="field">Cloud coverage<input id="weatherStrength" type="range" min="0" max="1" step="0.01"></label><label class="field">Cloud detail<select id="weatherQuality"><option value="0">Light</option><option value="1">Balanced</option><option value="2">Fine</option></select></label><label class="field">Cavity haze<input id="cavityHaze" type="range" min="0" max="1" step="0.01"></label><p class="micro">A thin dust study gives distant structures depth. Set to zero for a clear cavity.</p><p id="weatherProfile" class="micro"></p><p class="micro">Volumetric clouds follow the biome and move with simulation time. Atmosphere controls local air; cavity haze is independent. Captures use finer cloud sampling.</p>`;$('lighting').append(weather);
const materials=document.createElement('details');materials.open=true;materials.innerHTML=`<summary>Surface materials & shadows</summary><label class="check"><input id="richMaterials" type="checkbox"> Detailed Shade and Wound materials</label><label class="field">Structure shadows<select id="localShadows"><option value="0">Off</option><option value="1">Balanced</option><option value="2">Fine</option></select></label><p class="micro">Surface relief, rough ceramic, exposed metal and dust respond to the light. Nearby structures cast shadows across one another. Fine improves small shadow detail; photographs use finer shadow maps.</p>`;$('lighting').append(materials);
const chip=document.createElement('div');chip.className='field-chip';chip.innerHTML='<span id="fieldChipLabel"></span><button id="leaveWalk">Return to flight</button>';chip.hidden=true;document.querySelector('.view-top').append(chip);
const css=document.createElement('style');css.textContent='.field-chip{pointer-events:auto;position:absolute;top:85px;left:20px;display:flex;gap:12px;align-items:center;background:#111d23df;border:1px solid #71878366;border-radius:4px;padding:9px 12px;color:#dae5dc;font-size:11px}.field-chip[hidden]{display:none}.field-chip button{font-size:10px;padding:5px 8px}.world-geography{border-color:#77978355}.field-expeditions .two button{font-size:11px}.clean .field-chip{display:none}.world-geography .micro{line-height:1.55}';document.head.append(css);
for(const key of ['layoutVersion','axisLat','axisLon','waistWidth','transitionKm','shellThickness','geometryDetail','richMaterials','localShadows','wreckage','spaceEnvironment','clouds','weatherStrength','weatherQuality','cavityHaze'])$(key).addEventListener($(key).type==='range'?'input':'change',()=>{const s=A.getState();s[key]=$(key).type==='checkbox'?$(key).checked:Number($(key).value);if(['axisLat','axisLon','waistWidth','layoutVersion'].includes(key)){s.walkMode=false;s.siteId='';s.siteAnchor=null;s.walkPosition=null;}if(key==='layoutVersion'&&s.layoutVersion===1&&M.length(s.position)>s.radius-.5)s.position=M.mul(M.norm(s.position),s.radius-3);try{A.setState(s);}catch(e){A.toast(e.message);sync();}});
$('visitField').onclick=()=>visit($('fieldDestination').value);
$('walkField').onclick=()=>{const id=$('fieldDestination').value;if(!/^(biome|port)-/.test(id)){A.toast('Walking is available in the ten biome samples and the two entry courts.');return;}visit(id,{walk:true});};
$('returnField').onclick=restore;
$('leaveWalk').onclick=()=>{const s=A.getState();s.walkMode=false;s.walkPosition=null;s.position=M.add(s.position,M.mul(M.norm(s.position),-.035));changed(s,'Field site · free flight');};
const oldVisitBiome=$('visitBiome').onclick;$('visitBiome').onclick=()=>A.getState().layoutVersion===2?visit('biome-'+$('biomeDestination').value,{altitude:Number($('biomeAltitude').value)}):oldVisitBiome();
// Keep an exact selected ground location; select the nearest exact rim only if the ray enters a hole.
const oldSurface=$('seeSurface').onclick;let surfaceReturn=null;
function selectedSurface(force=false){const s=A.getState();if(s.layoutVersion!==2||!s.collection)return oldSurface();if(surfaceReturn&&!force){const previous=surfaceReturn;surfaceReturn=null;changed(previous,'Previous view');$('seeSurface').textContent='See surface ↓';return;}
 surfaceReturn=surfaceReturn||structuredClone(s);const distance=M.length(s.position)>s.radius?M.sphereDistance(s.position,s.forward,[0,0,0],s.radius):M.shellDistance(s.position,s.forward,s.radius);let q=Number.isFinite(distance)?M.norm(M.add(s.position,M.mul(s.forward,distance))):M.norm(s.position),rim=null;
 if(M.inBreach(q,s)){rim=W.nearestRim(q,s);const f=W.rimFrame(s,rim.index,rim.t);q=M.norm(M.add(f.point,M.mul(f.inland,3/s.radius)));}
 s.siteId='';s.siteAnchor=null;s.walkMode=false;s.walkPosition=null;s.position=M.mul(q,s.radius-3);s.speed=1;s.fov=76;s.projection='perspective';const close=W.nearestRim(q,s);if(s.era==='after'&&s.multipleWounds&&close.distance<1000){const f=W.rimFrame(s,close.index,close.t);s.forward=M.norm(M.add(M.mul(f.inland,-1),M.mul(q,.12)));}else s.forward=M.norm(M.add(M.basis(q).r,M.mul(q,.45)));s.up=M.basis(s.forward,M.mul(q,-1)).u;changed(s,W.sample(q,s).name+' · selected surface');$('seeSurface').textContent='Return to view ↑';};
$('seeSurface').onclick=()=>selectedSurface();
const oldSurfaceVisit=SphereSurface.visit,oldSurfaceReset=SphereSurface.resetReturn;
SphereSurface.visit=()=>A.getState().layoutVersion===2&&A.getState().collection?selectedSurface(true):oldSurfaceVisit();
SphereSurface.resetReturn=()=>{surfaceReturn=null;oldSurfaceReset();};
// Navigation cancels walking before the original destination handler changes the pose.
document.addEventListener('click',e=>{if(e.target.closest('[data-destination]:not([data-destination=surface]), [data-preset], #legacyStudy')){const s=A.getState();if(s.walkMode||s.siteId){s.walkMode=false;s.siteId='';s.siteAnchor=null;s.walkPosition=null;A.setState(s);}}},true);
function sync(){const s=A.getState();for(const key of ['layoutVersion','axisLat','axisLon','waistWidth','transitionKm','shellThickness','geometryDetail','richMaterials','localShadows','wreckage','spaceEnvironment','clouds','weatherStrength','weatherQuality','cavityHaze']){const el=$(key);if(el.type==='checkbox')el.checked=!!s[key];else el.value=String(s[key]);}for(const id of ['regionOrder','colorRichness'])$(id).closest('label').hidden=s.collection&&s.layoutVersion===2;for(const option of $('speed').options)if(Number(option.value)<1)option.disabled=s.layoutVersion!==2;$('cameraAltitude').min=s.layoutVersion===2?.001:1;const local=W.sample(M.norm(s.position),s);$('worldLocation').textContent=s.layoutVersion===2?local.name+' · image-derived reflectance':'Legacy layout retained for this scene';$('fieldChipLabel').textContent=(s.siteId?local.name+' · ':'')+'ON FOOT · 1.7 m eye height';chip.hidden=!s.walkMode;$('returnField').disabled=!returnState;$('weatherProfile').textContent=SphereWeatherProfiles[local.biome].name;$('fieldStatus').textContent=s.walkMode?'On foot · W A S D move · Shift run · Space jump. The site boundary is 1.08 km from its centre.':'Walkable samples span 2.4 km. Flight glides along solid ground; Wounds remain passable. Wound and exterior inspections meter exposure for their subject.';
 const map=document.querySelector('.keyboard-map');if(map){map.querySelector('.keyboard-map-title').textContent=s.walkMode?'WALK CONTROLS':'FLIGHT CONTROLS';map.querySelector('small').textContent=s.walkMode?'Shift · run   Space · jump':'Shift · fast   Space · shades';}
}
window.addEventListener('sphere-state-synced',sync);sync();
// Make the physical assumptions part of exported scenes and the in-app guide.
Object.assign(A.assumptions,{surface:'Version 2: one oriented habitat waist, supporting machinery and two polar entries. Far reflectance is the linear-sRGB mean of original biome images. Nearby colour comes from those images. Bounded 2.4-km sites add deterministic terrain and objects. The rest of the shell remains analytic.',geometry:'Analytic shell and star with camera-relative triangle geometry. Wound walls share a precise local boundary with the shell and use adaptive curved segments, angled strata and torn ribs. Shade service detail streams along its longitudinal fracture over a continuous analytic skin. LOD follows projected feature size, with subpixel retirement and retained world addresses. Thickness and engineering dimensions are provisional. Local field sites remain bounded. Shared logarithmic depth; panoramas assemble six geometry views.',lighting:'Finite stellar disk occlusion, image-derived 192-region first bounce, two camera-local directional shadow regions with approximate finite-star filtering, shared roughness/metalness/normal materials on Shade skin and Wound structures, and depth-clipped volumetric clouds with self-shadow sampling and optional tenuous cavity dust. ShellShine supplies a coarse environment reflection approximation; no reflection capture or converged global multiple scattering. No photometric calibration.',dynamics:'Inspection cameras follow the selected Shade frame through simulation and scrubbing; detach allows independent flight. Level lock removes roll within 1 km without changing pitch. Shade routes follow the habitat ribbons on actively maintained small circles. Artificial local 9.81 m/s² walking gravity and atmospheric containment are assumptions. Shade periods are authored, not Keplerian. Exterior fleets follow illustrative deterministic motion; warfare is not simulated. Instantaneous light; no retarded transport.',stars:'Illustrative distant stars and filtered debris silhouettes; nearby original wreckage geometry supplies parallax and detailed silhouettes. The earlier low-resolution illustration plates are archived. No astronomical catalogue or inherited external game assets.'});
const guide=document.createElement('div');guide.innerHTML='<h3>Designed shell and field expeditions</h3><p>World → Shell geography controls one habitat waist, three supporting machinery families and opposite polar entries. Old imported scenes retain their legacy layout. Explore → Field expeditions opens ten bounded terrain samples, entry service courts, the exact edge of a Wound, damaged Shade sections, and three exterior settings. On foot, use W A S D, Shift to run, Space to jump, and drag to look. Local geometry is included in perspective photographs and 360° panoramas.</p><h3>Materials and structure shadows</h3><p>Light → Surface materials &amp; shadows and Flight console control the detailed finishes and local shadows. Ceramic, metal and fracture faces use roughness and normal detail. Two shadow regions follow the camera; Fine gives small structures clearer shadows. Shadows are local approximations, and ShellShine remains a coarse estimate of the surrounding light.</p><h3>Physics of this study</h3><p id="worldPhysics"></p><p>Artificial gravity, active support, atmospheric containment and Shade propulsion remain story assumptions. Exposed shell thickness is provisional. Weather is a finite local optical approximation; climate, long-term debris orbits, damage propagation and actual warfare are not simulated.</p>';$('guide').insertBefore(guide,$('guide').querySelector('h3'));
function physics(){const p=W.physics(A.getState());$('worldPhysics').textContent='At this radius, light takes '+p.lightSeconds.toFixed(1)+' seconds to cross from the star to the shell. The three maintained Shade circuits take '+p.routes.map(r=>r.maintainedDays.toFixed(1)).join(', ')+' days; passive circular solar-mass orbits at those radii would take approximately '+p.routes.map(r=>r.keplerDays.toFixed(1)).join(', ')+' days. Lighting is currently evaluated at one simulation time.';}window.addEventListener('sphere-state-synced',physics);physics();
window.SphereEvolution={visit,restore,sync,physics};
})();
