/* Final layout moves existing controls and handlers into four accessible panels. */
(function(){
'use strict';const A=SphereApp,J=SphereJourney,$=id=>document.getElementById(id),tabs=document.querySelector('.tabs'),view=$('viewport');
const closePanel=document.createElement('button');closePanel.id='closeToolPanel';closePanel.className='quiet';closePanel.textContent='Close panel';closePanel.onclick=()=>{document.body.classList.add('panel-hidden');$('togglePanel').focus();};$('controls').prepend(closePanel);
const announcement=document.createElement('p');announcement.className='sr-only';announcement.setAttribute('role','status');announcement.setAttribute('aria-live','polite');view.append(announcement);
const journey=document.createElement('section');journey.id='journey';journey.className='tab-panel';journey.hidden=true;journey.innerHTML='<h3>Your journey</h3><p class="micro">Return restores the saved world and time, keeping your current play/pause and speed preference.</p><ol id="journeyEntries"></ol>';
$('photo').before(journey);
const lighting=$('lighting');lighting.classList.remove('tab-panel');lighting.hidden=false;const lightDetails=document.createElement('details');lightDetails.innerHTML='<summary>Rendering quality & advanced lighting</summary>';lightDetails.append(lighting);$('scene').append(lightDetails,$('specialistDestinations'));
const saved=$('saveBookmark').closest('details');journey.append(saved);
const saveView=document.createElement('button');saveView.id='captureSaveViewpoint';saveView.className='secondary full';saveView.textContent='Save viewpoint';saveView.onclick=()=>{$('bookmarkName').value=$('captureTitle').value;$('saveBookmark').click();};$('photo').append(saveView);
const title=document.createElement('label');title.className='field';title.innerHTML='Capture title<input id="captureTitle" maxlength="120" type="text">';$('photo').prepend(title);
const panorama=document.createElement('button');panorama.id='capturePanorama';panorama.className='secondary full';panorama.textContent='Take panorama';panorama.onclick=()=>A.capture({projection:'panorama'});$('capture').after(panorama);
const cancelPhoto=document.createElement('button');cancelPhoto.id='cancelPhoto';cancelPhoto.className='quiet full';cancelPhoto.textContent='Cancel photograph';cancelPhoto.hidden=true;cancelPhoto.onclick=()=>A.cancelCapture();panorama.after(cancelPhoto);
const captureStatus=document.createElement('p');captureStatus.id='captureStatus';captureStatus.className='micro';captureStatus.setAttribute('role','status');cancelPhoto.after(captureStatus);
const lightTab=tabs.querySelector('[data-tab=lighting]');lightTab.dataset.tab='journey';lightTab.textContent='Journey';tabs.replaceChildren(tabs.querySelector('[data-tab=camera]'),lightTab,tabs.querySelector('[data-tab=scene]'),tabs.querySelector('[data-tab=photo]'));
for(const tab of tabs.children){tab.id='tab-'+tab.dataset.tab;tab.setAttribute('aria-controls',tab.dataset.tab);const panel=$(tab.dataset.tab);panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby',tab.id);tab.addEventListener('click',()=>{document.body.classList.remove('panel-hidden');for(const other of tabs.children)other.tabIndex=other===tab?0:-1;});}
tabs.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const list=[...tabs.children],i=list.indexOf(document.activeElement),next=e.key==='Home'?0:e.key==='End'?list.length-1:(i+(e.key==='ArrowRight'?1:-1)+list.length)%list.length;list[next].click();list[next].focus();});
document.querySelector('.topbar').insertBefore(tabs,$('helpButton'));
const conditions=document.createElement('section');conditions.id='worldConditions';conditions.innerHTML='<h3>World conditions</h3><label class="field">Illumination<select id="worldIllumination"><option value="day">Current geometric lighting</option><option value="first-light">Illumination study · first light</option><option value="darkness">Illumination study · darkness arriving</option><option value="dark">Illumination study · dark</option></select></label><p class="micro">Artistic illumination studies change rendered light without changing eclipse geometry.</p><label class="field">Weather<select id="worldWeather"><option value="clear">Clear</option><option value="mixed">Mixed</option><option value="cover">Cover</option><option value="precipitation">Precipitation</option><option value="storm">Storm</option></select></label><p id="worldEraSummary" class="micro"></p><button id="worldClock" class="quiet">Go to the clock</button>';
$('scene').prepend(conditions);$('worldIllumination').onchange=()=>{const s=A.getState();s.placeScene=$('worldIllumination').value;A.setState(s);};$('worldWeather').onchange=()=>{const s=A.getState();SpherePlaces.conditions(s,s.placeScene,$('worldWeather').value);A.setState(s);};$('worldClock').onclick=()=>$('eraBefore').focus();
const timeline=document.querySelector('.timeline');timeline.append($('eraBefore'),$('eraAfter'));view.append(timeline);timeline.querySelector('.time-label').textContent='CLOCK';
// One persistent clock; the former console clock is retained only for handler compatibility.
for(const node of [$('consolePlay').parentElement,$('consoleScrub'),$('consoleReset')])node.hidden=true;
const strip=document.createElement('div');strip.id='locationStrip';strip.innerHTML='<div><strong id="locationName"></strong><span id="locationMode"></span></div>';strip.append($('browseBiomes'));view.append(strip);document.querySelector('.field-chip').hidden=true;
const tools=document.querySelector('.view-actions');view.append(tools);$('flightConsoleButton').textContent='Instruments';$('flightConsole').querySelector('strong').textContent='Instruments';const telemetry=document.querySelector('.telemetry');$('flightConsole').append(telemetry);const perf=$('performance'),diagnostics=document.createElement('details');diagnostics.innerHTML='<summary>Renderer diagnostics</summary>';diagnostics.append(perf);$('flightConsole').append(diagnostics);
for(const [id,label]of [['togglePanel','Show or hide controls'],['fullscreen','Enter or exit full screen']]){$(id).setAttribute('aria-label',label);$(id).title=label;}
const quiet=document.createElement('button');quiet.id='quietView';quiet.textContent='Quiet';quiet.onclick=()=>{document.body.classList.toggle('clean');quiet.textContent=document.body.classList.contains('clean')?'Show controls':'Quiet';};tools.append(quiet);
$('togglePanel').onclick=()=>{document.body.classList.toggle('panel-hidden');if(document.body.classList.contains('panel-hidden'))$('togglePanel').focus();};
window.addEventListener('keydown',e=>{if(e.key==='Escape'){document.body.classList.remove('clean');quiet.textContent='Quiet';if(!document.fullscreenElement){document.body.classList.add('panel-hidden');$('togglePanel').focus();}}});
document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'Exit full screen':'Full screen';});$('fullscreen').textContent='Full screen';
// Overview routes now belong to Explore. Keep old button IDs reachable in the specialist disclosure.
const overview=document.createElement('details');overview.innerHTML='<summary>Overview shortcuts</summary>';overview.append(document.querySelector('.journeys'));$('specialistDestinations').append(overview);
let defaultTitle='',lastIdentity='';
function sync(){const s=A.getState(),location=J.current(),label=location.title+(location.region&&location.region!==location.title?' · '+location.region:'');$('locationName').textContent=label;$('viewTitle').textContent=location.title;
 const altitude=s.shadeAttachment!==null?SphereInspection.surface(s).altitude:SphereLanding.heightAboveGround(s);$('locationMode').textContent=(s.walkMode?'On foot':s.shadeAttachment!==null?'Following Shade '+s.shadeAttachment:'Free flight')+' · '+(altitude<1?(altitude*1000).toFixed(1)+' m':altitude.toLocaleString(undefined,{maximumFractionDigits:1})+' km')+' above '+(s.shadeAttachment!==null?'Shade skin':'ground')+(s.placeScene!=='day'?' · illumination study: '+s.placeScene:'');
 $('fieldChipLabel').textContent=label+' · On foot';$('worldIllumination').value=s.placeScene;$('worldWeather').value=s.placeWeather;$('worldEraSummary').textContent=(s.era==='before'?'Before':'After')+' attack · use the persistent clock to change era.';
 if($('captureTitle').value===defaultTitle||!$('captureTitle').value)$('captureTitle').value=location.title;defaultTitle=location.title;
 if(lastIdentity!==label){lastIdentity=label;history();}
 $('speedReadout').previousElementSibling.textContent='AVAILABLE SPEED';$('play').setAttribute('aria-label',s.playing?'Pause clock':'Play clock');$('resetTime').setAttribute('aria-label','Reset clock');
}
function history(){const list=$('journeyEntries');list.replaceChildren();for(const entry of J.entries){const row=document.createElement('li'),button=document.createElement('button');button.className='secondary';button.textContent=entry.title+' · '+(entry.state.walkMode?'on foot':Math.abs(entry.state.radius-SphereMath.length(entry.state.position)).toLocaleString(undefined,{maximumFractionDigits:3})+' km above shell')+' · '+entry.state.era+' attack · '+Math.round(entry.state.time)+' s';button.onclick=()=>J.visit(entry.state,entry.title);row.append(button);list.append(row);}const current=document.createElement('li');current.textContent=J.current().title+' · current location';current.setAttribute('aria-current','location');list.append(current);}
window.addEventListener('sphere-history-changed',history);window.addEventListener('sphere-state-synced',sync);window.addEventListener('sphere-telemetry',sync);window.addEventListener('sphere-travel-committed',sync);
window.addEventListener('sphere-travel-status',e=>{const pending=e.detail.state==='preparing'||e.detail.held;for(const id of ['capture','capturePanorama','recordClip','consolePhoto'])$(id).disabled=!!pending;$('captureStatus').textContent=pending?'Capture is unavailable while travel prepares or restores support.':'';if(!pending)announcement.textContent=e.detail.state==='arrived'?'Arrived at '+J.current().title+'.':e.detail.error||e.detail.state;});
window.addEventListener('sphere-capture-status',e=>{$('captureStatus').textContent=e.detail.message;cancelPhoto.hidden=e.detail.state!=='preparing';$('capturePanorama').disabled=e.detail.state==='preparing';$('visitPlace').disabled=e.detail.state==='preparing';});
// Deliberate camera buttons invalidate pending travel, even if their pose rounds to the same numbers.
for(const button of document.querySelectorAll('[data-turn],#levelCamera,#faceSurface,#faceStar,#inspectBelow,#leaveWalk,#consoleAttachment'))button.addEventListener('click',()=>window.dispatchEvent(new Event('sphere-user-navigation-intent')),true);
lightTab.tabIndex=-1;tabs.firstElementChild.click();sync();history();
})();
