/* An explicit live destination. Old scene imports do not acquire a province. */
(function(){
'use strict';const A=SphereApp,P=SphereWatershed,$=id=>document.getElementById(id);let previous=null;
const panel=document.createElement('details');panel.open=true;panel.id='watershedExpedition';panel.innerHTML=`<summary>Watershed · the river gardens</summary>
<p class="micro">A connected neighbourhood of irregular catchments, receiving lakes and open country surrounds the original 640 km river garden. Ivory terraces and copper colonnades shelter water works among planted courts.</p>
<label class="field">Arrival<select id="watershedArrival"><option value="neighbourhood">Connected catchments · 40,000 km</option><option value="region">Receiving reaches · 10,000 km</option><option value="province">The whole watershed · 1,100 km above the shell</option><option value="approach">River country · 48 km approach</option><option value="garden" selected>Water garden · 1 km above the landscape</option><option value="terrace">The open terrace · 6 m above its floor</option></select></label>
<div class="two"><button id="visitWatershed" class="secondary">Enter the province</button><button id="returnWatershed" class="quiet">Return to previous view</button></div>
<p id="watershedStatus" class="micro"></p>`;
$('camera').prepend(panel);
async function visit(name=$('watershedArrival').value){const state=A.getState();$('visitWatershed').disabled=true;$('watershedStatus').textContent='Preparing the river gardens…';try{const province=SpherePacks.activate(state);await P.prepare(province);const next=P.view(province,name);if(A.renderer.geometry)for(const mesh of P.geometry(next))while(!A.renderer.geometry.stage(mesh,4))await new Promise(r=>requestAnimationFrame(r));const current=A.getState();if(state.playing&&current.playing)current.time=state.time;if(JSON.stringify(current)!==JSON.stringify(state)){A.toast('Arrival cancelled because the scene changed.');sync();return;}previous=previous||structuredClone(state);SphereJourney.remember();next.speed=state.speed;next.time=A.getState().time;A.setState(next);$('viewTitle').textContent='Watershed · '+({neighbourhood:'connected catchments',region:'receiving reaches',province:'the river gardens',approach:'river country',garden:'water garden',terrace:'the open terrace'}[name]);window.dispatchEvent(new Event('sphere-view-changed'));$('viewport').focus({preventScroll:true});sync();return next;}catch(e){A.toast(e.message);}finally{$('visitWatershed').disabled=false;}}
function restore(){if(previous){A.setState(previous);previous=null;$('viewTitle').textContent='Previous view';window.dispatchEvent(new Event('sphere-view-changed'));sync();}}
function sync(){const s=A.getState();$('returnWatershed').disabled=!previous;$('watershedStatus').textContent=P.enabled(s)?(s.packAddress?'Watershed pack 1 · geography 1 / art 1 · seed ':'Province 1 · seed ')+s.provinceSeed+' · saved with this scene. Flights, photographs and panoramas share the same landscape.':'Entering adds the Watershed neighbourhood to this scene. Existing saved worlds retain their original arrangement.';}
$('visitWatershed').onclick=()=>visit();$('returnWatershed').onclick=restore;window.addEventListener('sphere-state-synced',sync);sync();
A.assumptions.watershedPack='Explicit schema-1 Watershed pack address, geography/art revisions and seed. Original 640 km terrain retained. Surrounding irregular drainage, bank routes and lake are analytic shell materials with shared CPU masks, not displaced regional terrain or a hydrodynamic simulation. Walking remains bounded to a local 2.4 km patch.';
A.assumptions.watershed='Optional Watershed province revision 1, seed and unit-vector anchor saved independently of shell layout 2. A 640-km deterministic catchment graph supplies terrain, receiving basins and smoothed river ribbons. Curved water-garden structures are shared rendered/collision geometry. Water is a static surface, not a hydrodynamic simulation. Local canopy and a six-metre terrace inspection are included; this is not a new walking level.';
window.SphereWatershedJourney={visit,restore,openLink:()=>{const link=new URLSearchParams(location.search);if(link.get('province')==='watershed')return visit(['neighbourhood','region','province','approach','garden','terrace'].includes(link.get('view'))?link.get('view'):'garden');}};

})();
