const {chromium}=require(process.env.SPHERE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.SPHERE_BROWSER});try{
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],baseline=!!process.env.SPHERE_ASCENT_BASELINE,dir=path.resolve('work/screenshots/ascent');fs.mkdirSync(dir,{recursive:true});page.setDefaultTimeout(180000);page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8766/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.SphereLoading?.ready);await page.evaluate(()=>SphereApp.setBusy(true));console.log('Ascent renderer ready');
 const records=[];
 for(const altitude of [70,120,449.2,1100,256267,2040000,14960000,70000000]){const result=await page.evaluate(async altitude=>{
  const M=SphereMath,R=SphereApp.renderer,s=await SpherePlaces.destination({...M.defaultState(),collection:true,time:4882600},'biome-8','ground','day','mixed'),q=M.norm(s.position),up=M.mul(q,-1),heading=M.norm(M.sub(s.forward,M.mul(up,M.dot(s.forward,up))));s.position=M.mul(q,s.radius-altitude);s.forward=M.norm(M.add(heading,M.mul(up,.24)));s.up=M.basis(s.forward,up).u;s.walkMode=false;s.walkSurface=false;s.walkPosition=null;s.siteId='';s.siteAnchor=null;s.geometryDetail=false;SphereApp.setState(s);await R.prepare(s,{aspect:16/10});R.draw(s,1440,900,{exportFrame:true});R.draw(s,1440,900,{exportFrame:true});
  const gl=R.gl,v=R.weather,w=v.vw,h=v.vh,data=new Float32Array(w*h*4);gl.bindFramebuffer(gl.FRAMEBUFFER,v.volumeFbo);gl.readBuffer(gl.COLOR_ATTACHMENT1);gl.readPixels(0,0,w,h,gl.RGBA,gl.FLOAT,data);gl.bindFramebuffer(gl.FRAMEBUFFER,null);
  const alpha=(x,y)=>1-(data[(y*w+x)*4]+data[(y*w+x)*4+1]+data[(y*w+x)*4+2])/3;let spikes=0,tested=0,rough=0,nonfinite=0;const spikePoints=[];
  for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const c=alpha(x,y),neighbours=[alpha(x-1,y),alpha(x+1,y),alpha(x,y-1),alpha(x,y+1)],mean=neighbours.reduce((a,b)=>a+b,0)/4,delta=Math.abs(c-mean);rough+=delta;spikes+=delta>.15?1:0;if(delta>.15&&spikePoints.length<20)spikePoints.push({x,y,c,mean});tested++;if(!Number.isFinite(c))nonfinite++;}
  const png=R.canvas.toDataURL();let diagnostics=[];
  if(spikes/tested>.003&&altitude>=160){const original=v.farProgram,debug=SphereVolume.far.replace('scattering=vec4(light,1.);transmission=vec4(tr,depth);', 'float ground=heightRoots(d,0.).y;scattering=vec4(clamp((hit-ground)/ground*1e6,-60000.,60000.),abs(dot(d,normalize(d*ground-cameraUp*(radius-height)))),ground/1e6,1.);transmission=vec4(tr,depth);');v.farProgram=SphereGLProgram(gl,SphereShaders.vertex,debug);R.draw(s,1440,900,{exportFrame:true});gl.bindFramebuffer(gl.FRAMEBUFFER,v.volumeFbo);gl.readBuffer(gl.COLOR_ATTACHMENT0);
   for(const point of spikePoints){const pixel=new Float32Array(4);gl.readPixels(point.x,point.y,1,1,gl.RGBA,gl.FLOAT,pixel);diagnostics.push({...point,groundErrorPpm:pixel[0],slant:pixel[1],groundMillionKm:pixel[2]});}gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.deleteProgram(v.farProgram.p);v.farProgram=original;}
  return {diagnostics,altitude,spikes,tested,spikeFraction:spikes/tested,roughness:rough/tested,nonfinite,state:s,error:R.error(),png};
 },altitude);fs.writeFileSync(path.join(dir,(baseline?'before-':'after-')+altitude+'.png'),Buffer.from(result.png.split(',')[1],'base64'));delete result.png;records.push(result);fs.writeFileSync(path.join(dir,'latest.json'),JSON.stringify(records,null,2));assert.equal(result.error,0);assert.equal(result.nonfinite,0);console.log('Ascent',altitude,JSON.stringify({spikeFraction:result.spikeFraction,roughness:result.roughness}));if(!baseline)assert(result.spikeFraction<.003,'Distant cloud speckling: '+result.spikeFraction);}
 fs.writeFileSync(path.join(dir,(baseline?'before':'after')+'.json'),JSON.stringify({records,errors},null,2));assert.deepEqual(errors,[]);console.log(baseline?'Baseline captured':'PASS filtered ascent at local, province and cavity distances');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
