const {chromium}=require(process.env.SPHERE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.SPHERE_BROWSER?{executablePath:process.env.SPHERE_BROWSER}:{})});try{
 const page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(120000);
 await page.goto(process.env.SPHERE_URL||'http://127.0.0.1:8766/',{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.SphereEvolution&&document.getElementById('flightConsole'));await page.evaluate(()=>SphereApp.setBusy(true));
 const dir=path.resolve('work/screenshots/continuity');fs.mkdirSync(dir,{recursive:true});
 const rays=await page.evaluate(()=>{const A=SphereApp,M=SphereMath,W=SphereWorld,R=A.renderer,gl=R.gl,ids={'Inner surface':0,Shade:1,Star:2,'Open space':3,'Stellar station':4};let probes=0,mismatch=0;const failures=[],w=160,h=100;
  for(const index of [0,2,5])for(const angle of [.03,Math.PI/2,3.7])for(const altitude of [.02,5,300]){const f=W.rimFrame(A.getState(),index,angle),s={...A.getState(),position:M.add(M.mul(f.point,A.getState().radius-altitude),M.mul(f.inland,-altitude)),forward:M.norm(M.add(f.inland,M.mul(f.point,.7))),up:M.mul(f.point,-1),fov:86,viewMode:'objectid',geometryDetail:false,routeShades:false,starStation:false,antialias:0};R.draw(s,w,h);const px=new Uint8Array(w*h*4);gl.readPixels(0,0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,px);const b=M.basis(s.forward,s.up);
   for(let y=0;y<h;y++)for(let x=0;x<w;x++){const d=M.ray((x+.5)/w*2-1,(y+.5)/h*2-1,w/h,s.fov,b),hit=M.trace(s.position,d,s),gpu=Math.round(px[(y*w+x)*4]/255*4);probes++;if(ids[hit.kind]!==gpu){mismatch++;if(failures.length<8)failures.push({index,angle,altitude,x,y,cpu:hit.kind,gpu});}}
  }return {probes,mismatch,failures,gl:R.error()};});console.log('Close Wound rays',rays);assert.equal(rays.gl,0);assert(rays.mismatch/rays.probes<.0001);
 const shadeRays=await page.evaluate(()=>{const A=SphereApp,R=A.renderer,M=SphereMath,gl=R.gl,ids={'Inner surface':0,Shade:1,Star:2,'Open space':3,'Stellar station':4},w=64,h=48;let probes=0,mismatch=0;const failures=[];
  for(const shape of ['disk','square','cap','trimmed'])for(const id of [0,7,8])for(const height of [.02,2]){const s={...A.getState(),siteId:'shade-'+id,shadeShape:shape,geometryDetail:false,starStation:false,viewMode:'objectid',antialias:0},anchor=SphereSites.shadeSection(s);s.position=anchor.world([-height,height,height*3.75]);s.forward=M.norm(M.sub(anchor.world([height*2.5,0,0]),s.position));s.up=anchor.basis[1];s.fov=78;R.draw(s,w,h);const px=new Uint8Array(w*h*4);gl.readPixels(0,0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,px);const b=M.basis(s.forward,s.up);
   for(let y=0;y<h;y++)for(let x=0;x<w;x++){const d=M.ray((x+.5)/w*2-1,(y+.5)/h*2-1,w/h,s.fov,b),cpu=M.trace(s.position,d,s),gpu=Math.round(px[(y*w+x)*4]/255*4);probes++;if(ids[cpu.kind]!==gpu){mismatch++;if(failures.length<5)failures.push({shape,id,height,x,y,cpu:cpu.kind,gpu});}}
  }return {probes,mismatch,failures,gl:R.error()};});console.log('Close Shade rays',shadeRays);assert.equal(shadeRays.gl,0);assert(shadeRays.mismatch/shadeRays.probes<.0001);
 const captures=[];
 for(const id of ['rim','shade-0','shade-7','shade-8']){const result=await page.evaluate(async id=>{const A=SphereApp,R=A.renderer;SphereEvolution.visit(id);const s=A.getState();await R.prepare(s);R.draw(s,1600,1000,{exportFrame:true});return {id,image:R.canvas.toDataURL('image/png'),state:s,info:R.renderInfo,gl:R.error()};},id);fs.writeFileSync(path.join(dir,id+'.png'),Buffer.from(result.image.split(',')[1],'base64'));delete result.image;captures.push(result);console.log(id,result.info.geometry);assert.equal(result.gl,0);assert(result.info.geometry?.groups>0);}
 const localPose=()=>page.evaluate(()=>{const s=SphereApp.getState(),p=SphereInspection.plate(s),M=SphereMath;return {position:s.position,time:s.time,local:p?[p.right,p.normal,p.up].map(b=>M.dot(M.sub(s.position,M.mul(p.center,s.radius)),b)):null};});
 await page.evaluate(()=>{SphereEvolution.visit('shade-0');SphereApp.renderer.draw(SphereApp.getState(),640,400);SphereApp.setBusy(false);});
 await page.click('#flightConsoleButton');await page.selectOption('#consoleRate','600');const before=await localPose();await page.click('#consolePlay');await page.waitForTimeout(700);await page.click('#consolePlay');const after=await localPose();assert(after.time>before.time+50);assert(Math.hypot(...after.local.map((v,i)=>v-before.local[i]))<.000005,'Play must follow the Shade');assert(Math.hypot(...after.position.map((v,i)=>v-before.position[i]))>1000,'The world-space camera must move with the Shade');
 await page.locator('#consoleScrub').evaluate(el=>{el.value='10000';el.dispatchEvent(new Event('input',{bubbles:true}));});const scrubbed=await localPose();assert(Math.hypot(...scrubbed.local.map((v,i)=>v-before.local[i]))<.000005);
 await page.click('#consoleAttachment');const detached=await localPose();await page.click('#consolePlay');await page.waitForTimeout(400);await page.click('#consolePlay');const detachedAfter=await localPose();assert.deepEqual(detachedAfter.position,detached.position);
 await page.click('#consoleAttachment');await page.locator('#viewport').focus();const flightBefore=await localPose();await page.keyboard.down('w');await page.waitForTimeout(350);await page.keyboard.up('w');const flightAfter=await localPose();assert(Math.hypot(...flightAfter.local.map((v,i)=>v-flightBefore.local[i]))>.001,'Keyboard flight still works after using console buttons');
 await page.click('#closeFlightConsole');await page.click('#fullscreen');assert(await page.evaluate(()=>document.fullscreenElement?.id==='viewport'));await page.click('#flightConsoleButton');await page.locator('#consoleExposure').evaluate(el=>{el.value='0.7';el.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal(await page.evaluate(()=>SphereApp.getState().exposure),.7);await page.click('#consoleLevel');assert.equal(await page.evaluate(()=>SphereApp.getState().surfaceLock),false);await page.click('#consoleLevel');
 await page.screenshot({path:path.join(dir,'fullscreen-console.png')});await page.evaluate(()=>document.exitFullscreen());
 const travel=await page.evaluate(()=>{const A=SphereApp,M=SphereMath,R=A.renderer;A.setBusy(true);SphereEvolution.visit('shade-0');const s=A.getState(),anchor=SphereSites.shadeSection(s),records=[];
  for(const distance of [0,2,20,100,500]){s.position=anchor.world([-.3,.2,distance+.75]);const t=performance.now();R.draw(s,1280,720);R.gl.finish();records.push({distance,cpu:performance.now()-t,groups:R.renderInfo.geometry.groups,triangles:R.renderInfo.geometry.triangles,cache:SphereEdges.cacheSize});}return records;});console.log('Travel',travel);assert(travel.every(r=>r.groups>0&&r.groups<1200&&r.cache<=1200));
 fs.writeFileSync(path.join(dir,'verification.json'),JSON.stringify({rays,shadeRays,captures,travel,attachment:{before,after,scrubbed,detachedAfter},errors},null,2));assert.deepEqual(errors,[]);console.log('PASS close boundary precision, all Shade inspections, Play/scrub attachment, detach, keyboard flight, fullscreen controls and long edge travel.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
