const assert=require('node:assert/strict'),M=require('../math.js');require('../collection.js');require('../biomes.js');require('../world-palette.js');require('../world.js');require('../field-sites.js');
const W=SphereWorld,C=SphereCollection,S=SphereSites,B=SphereBiomes,s={...M.defaultState(),collection:true};
const near=(a,b,e=1e-8)=>assert(Math.abs(a-b)<e,`${a} != ${b}`);
assert.deepEqual(M.validate(s),s);const old={...s};for(const k of Object.keys(W.defaults))delete old[k];assert.equal(M.validate(old).layoutVersion,1);assert.throws(()=>M.validate({...s,siteId:'exterior-0',siteAnchor:null}));assert.throws(()=>M.validate({...s,layoutVersion:99}));assert.throws(()=>M.validate({...s,walkMode:true,siteId:'rim',siteAnchor:[0,0,1],walkPosition:[0,.1,0]}));
for(const axisLat of [-90,-12,63,90])for(const axisLon of [-180,23,180]){const state={...s,axisLat,axisLon};const f=W.frame(state);near(M.dot(f.axis,f.right),0);near(M.dot(f.axis,f.up),0);near(M.dot(f.up,f.right),0);near(M.length(f.axis),1);assert.equal(W.sample(f.axis,{...state,multipleWounds:false}).id,15);assert.equal(W.sample(M.mul(f.axis,-1),{...state,multipleWounds:false}).id,15);for(let j=0;j<8;j++){const q=W.direction(.1,j*.4,state),c=W.coordinates(q,state);near(c.lat,.1);near(c.lon,j*.4);}}
for(let id=0;id<10;id++){const q=W.locateBiome(id,s);assert(!C.missing(q,s),`Biome ${id} is missing`);assert.equal(B.region(q,s),id,`Biome destination ${id}`);}
let samples=0;for(let j=0;j<6;j++)for(let k=0;k<60;k++){const q=W.boundaryPoint(j,k*Math.PI/30);near(C.woundDistance(q,C.wounds[j]),1,1e-10);samples++;}for(let j=0;j<6;j++){const q=W.boundaryPoint(j,.7321),rim=W.nearestRim(q,s);assert.equal(rim.index,j);assert(rim.distance<.001,`Rim nearest precision ${rim.distance} km`);}
for(const era of ['before','after']){const st={...s,era};for(const p of C.plates(st))assert.equal(p.layoutVersion,2);const damage=C.plates(st).filter(p=>p.damage);assert.equal(damage.length,era==='before'?0:5);}
const exterior={...s,routeShades:false,starStation:false,position:M.mul(W.frame(s).axis,s.radius+1000)};assert.equal(C.visibility(exterior.position,{...exterior,multipleWounds:false},64),0);assert.equal(C.visibility(M.mul(C.wounds[0].axis,s.radius+1000),exterior,64),1);
for(let j=0;j<100;j++){const q=M.norm([Math.sin(j*3.7),Math.cos(j*1.7),Math.sin(j+.4)]);assert.equal(C.visibility(M.mul(q,s.radius),{...s,routeShades:false,starStation:false,multipleWounds:false},19),1,'The shell must not shadow its own rounded surface receiver');}
const outsideView=M.mul(C.wounds[0].axis,s.radius*1.02),throughHole=M.norm(M.add(M.mul(C.wounds[0].axis,-1),M.mul(C.wounds[0].tangent,.08))),farWall=M.trace(outsideView,throughHole,{...s,routeShades:false,starStation:false});assert.equal(farWall.kind,'Inner surface');assert(farWall.distance>s.radius,'Looking inward through a Wound must reveal the opposite wall');
let terrainChecks=0;for(let id=0;id<10;id++){const state={...s,siteId:'biome-'+id,siteAnchor:W.locateBiome(id,s)},mesh=S.site(state);assert(mesh.count>50000);assert(mesh.vertices.every(Number.isFinite));for(let j=1;j<12;j++){const x=Math.sin(j)*.75,z=Math.cos(j*1.7)*.75,h=S.ground(mesh,x,z),p=mesh.world([x,h+.2,z]),hit=S.trace(p,M.mul(mesh.basis[1],-1),{...state,position:p},()=>({distance:Infinity,kind:'none'}));assert(hit.distance<=.20001&&hit.distance>=0);terrainChecks++;}
 S.enterWalk(state);assert.equal(M.validate(state).walkMode,true);const before=state.position.slice();for(let j=0;j<120;j++)S.step(state,new Set(['KeyW']),1/60);const travelled=M.length(M.sub(state.position,before));assert(travelled>.002&&travelled<.0065,`walking speed ${id}: ${travelled}`);assert(state.walkPosition[1]>=S.ground(mesh,state.walkPosition[0],state.walkPosition[2])+S.EYE-.00001);const restored=M.validate(M.sceneRecord(state).state);assert.deepEqual(restored.walkPosition,state.walkPosition);assert.deepEqual(restored.position,state.position);assert.deepEqual(restored.siteAnchor,state.siteAnchor);const floor=state.walkPosition[1];S.step(state,new Set(['Space']),.05);assert(state.walkPosition[1]>floor);for(let j=0;j<100;j++)S.step(state,new Set(),1/60);near(state.walkPosition[1],S.ground(mesh,state.walkPosition[0],state.walkPosition[2])+S.EYE+.0005,.000001);
}
const physics=W.physics(s);near(physics.lightSeconds,499.00478383615643,.000001);assert(physics.routes.every(r=>r.keplerDays>r.maintainedDays*10));
console.log('PASS v2 and legacy state validation, oriented waist and opposing ports, all ten destinations,',samples,'exact rim probes, sub-metre nearest rims, three damage families, exterior shell occlusion,',terrainChecks,'terrain rays, walk/jump/restore and physical units.');
