const {chromium}=require(process.env.SPHERE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.SPHERE_BROWSER?{executablePath:process.env.SPHERE_BROWSER}:{})});try{
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto(process.env.SPHERE_URL||'http://127.0.0.1:8766/',{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>!!window.SphereEvolution,{timeout:120000});await page.evaluate(()=>SphereApp.setBusy(true));
 console.log('Renderer loaded');
 const geo=await page.evaluate(()=>{const A=SphereApp,M=SphereMath,W=SphereWorld,R=A.renderer,gl=R.gl,s={...A.getState(),geometryDetail:false,viewMode:'geographyid',antialias:0},w=96,h=64;let probes=0,mismatch=0,maxBlend=0;const failures=[];for(const era of ['before','after'])for(const axisLat of [-50,63,90]){s.era=era;s.axisLat=axisLat;R.draw(s,w,h);const pixels=new Uint8Array(w*h*4);gl.readPixels(0,0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,pixels);const b=M.basis(s.forward,s.up);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const d=M.ray((x+.5)/w*2-1,(y+.5)/h*2-1,w/h,s.fov,b),t=M.shellDistance(s.position,d,s.radius),q=M.norm(M.add(s.position,M.mul(d,t))),cpu=W.sample(q,s),j=(y*w+x)*4,a=Math.round(pixels[j]/17),bb=Math.round(pixels[j+1]/17),blend=pixels[j+2]/255;probes++;const cw=Array(16).fill(0),gw=Array(16).fill(0);cw[cpu.a]+=1-cpu.blend;cw[cpu.b]+=cpu.blend;gw[a]+=1-blend;gw[bb]+=blend;const error=Math.max(...cw.map((v,i)=>Math.abs(v-gw[i])));if(error>.004){mismatch++;if(failures.length<8)failures.push({era,axisLat,x,y,cpu:[cpu.a,cpu.b,cpu.blend],gpu:[a,bb,blend],error,lat:cpu.lat,lon:cpu.lon});}maxBlend=Math.max(maxBlend,error);}}return {probes,mismatch,maxBlend,failures,gl:R.error()};});console.log('Geography',JSON.stringify(geo));assert.equal(geo.gl,0);
 const dir=path.resolve(__dirname,'../work/screenshots');fs.mkdirSync(dir,{recursive:true});const captures=[];
 for(const id of ['biome-0','biome-1','biome-2','biome-3','biome-4','biome-5','biome-6','biome-7','biome-8','biome-9','rim','port-0','port-1','shade-0','shade-7','shade-8','exterior-0','exterior-1','exterior-2']){
  const result=await page.evaluate(async id=>{const A=SphereApp;SphereEvolution.visit(id,{walk:id.startsWith('biome-')});const s=A.getState();if(id.startsWith('biome-')){s.atmosphere=1;s.weatherStrength=.65;s.clouds=true;A.setState(s);}await A.renderer.prepare(s);A.renderer.draw(s,1280,800,{exportFrame:true});const gl=A.renderer.gl,pixels=new Uint8Array(1280*800*4);gl.readPixels(0,0,1280,800,gl.RGBA,gl.UNSIGNED_BYTE,pixels);let sum=0,bright=0;for(let j=0;j<pixels.length;j+=4){sum+=pixels[j]+pixels[j+1]+pixels[j+2];if(pixels[j]+pixels[j+1]+pixels[j+2]>12)bright++;}return {id,gl:A.renderer.error(),mean:sum/(1280*800*3),bright:bright/(1280*800),info:A.renderer.renderInfo,pose:s.position,image:A.renderer.canvas.toDataURL('image/png')};},id);
  const image=result.image;delete result.image;fs.writeFileSync(path.join(dir,id+'.png'),Buffer.from(image.split(',')[1],'base64'));captures.push(result);console.log(id,{gl:result.gl,mean:result.mean,geometry:result.info.geometry});assert.equal(result.gl,0);assert(result.mean>1);assert(result.info.geometry?.groups>0);
 }
 const walking=await page.evaluate(()=>{const A=SphereApp,S=SphereSites;SphereEvolution.visit('biome-0',{walk:true});let s=A.getState();const before=s.position.slice(),time=s.time;for(let j=0;j<120;j++)S.step(s,new Set(['KeyW']),1/60);A.setState(s);const text=JSON.stringify(A.record());const restored=SphereMath.validate(JSON.parse(text).state);return {distance:SphereMath.length(SphereMath.sub(s.position,before)),same:restored.position.every((v,i)=>Math.abs(v-s.position[i])<1e-8)&&JSON.stringify(restored.walkPosition)===JSON.stringify(s.walkPosition),walk:s.walkMode,timeUnchanged:s.time===time};});console.log('Walking',walking);assert(walking.distance>.002&&walking.distance<.007);assert(walking.same&&walking.walk&&walking.timeUnchanged);
 const clouds=await page.evaluate(()=>{const A=SphereApp,M=SphereMath;SphereEvolution.visit('biome-1',{walk:true});const s=A.getState();s.forward=M.norm(M.add(M.mul(M.norm(s.position),-.6),SphereSites.shellFrame(s.siteAnchor)[2]));s.up=M.basis(s.forward,M.mul(M.norm(s.position),-1)).u;s.atmosphere=1;s.weatherStrength=.95;const R=A.renderer,gl=R.gl,w=180,h=120,read=()=>{const p=new Uint8Array(w*h*4);gl.readPixels(0,0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,p);return p;};R.draw({...s,clouds:false},w,h);const clear=read();R.draw({...s,clouds:true},w,h);const cloud=read();let difference=0;for(let i=0;i<clear.length;i+=4)difference+=Math.abs(clear[i]-cloud[i])+Math.abs(clear[i+1]-cloud[i+1])+Math.abs(clear[i+2]-cloud[i+2]);return {difference,gl:R.error()};});console.log('Clouds',clouds);assert(clouds.difference>1000);assert.equal(clouds.gl,0);
 const panorama=await page.evaluate(()=>{const A=SphereApp;SphereEvolution.visit('biome-4',{walk:true});const s={...A.getState(),projection:'panorama'};A.renderer.draw(s,1024,512,{exportFrame:true});return {info:A.renderer.renderInfo,gl:A.renderer.error(),image:A.renderer.canvas.toDataURL('image/png')};});fs.writeFileSync(path.join(dir,'local-panorama.png'),Buffer.from(panorama.image.split(',')[1],'base64'));delete panorama.image;console.log('Panorama',panorama);assert.equal(panorama.info.panoramaFaces,6);assert.equal(panorama.gl,0);
 const keyboard=await page.evaluate(()=>{SphereEvolution.visit('biome-2',{walk:true});SphereApp.setBusy(false);return {position:SphereApp.getState().position,time:SphereApp.getState().time};});await page.locator('#viewport').focus();await page.keyboard.down('w');await page.waitForTimeout(700);await page.keyboard.up('w');await page.keyboard.press('Space');await page.waitForTimeout(80);const moved=await page.evaluate(()=>({s:SphereApp.getState(),gl:SphereApp.renderer.error()}));assert(moved.s.walkMode);assert.equal(moved.s.playing,false);assert.equal(moved.s.time,keyboard.time);assert(Math.hypot(...moved.s.position.map((v,i)=>v-keyboard.position[i]))>.0003);assert.equal(moved.gl,0);await page.click('#leaveWalk');assert.equal(await page.evaluate(()=>SphereApp.getState().walkMode),false);await page.evaluate(()=>SphereApp.setBusy(true));
 const woundAir=await page.evaluate(()=>{const A=SphereApp,M=SphereMath;SphereEvolution.visit('rim');const s=A.getState(),R=A.renderer,gl=R.gl;s.forward=M.norm(s.position);s.up=M.basis(s.forward).u;s.fov=10;s.antialias=0;const w=96,h=64,read=()=>{const px=new Uint8Array(w*h*4);gl.readPixels(0,0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,px);return px;};R.draw({...s,atmosphere:0},w,h);const clear=read();R.draw({...s,atmosphere:1,clouds:true,weatherStrength:1},w,h);const cloudy=read();return {difference:clear.reduce((sum,v,i)=>sum+Math.abs(v-cloudy[i]),0),gl:R.error()};});assert.equal(woundAir.difference,0,'Contained weather must not cover the empty side of a Wound');assert.equal(woundAir.gl,0);
 const surfaceStart=await page.evaluate(()=>{const A=SphereApp,M=SphereMath,s=A.getState(),f=SphereWorld.rimFrame(s);SphereSurface.resetReturn();s.siteId='';s.siteAnchor=null;s.walkMode=false;s.walkPosition=null;const q=M.norm(M.add(f.point,M.mul(f.inland,-3000/s.radius)));s.position=M.mul(q,s.radius*.75);s.forward=q;s.up=M.basis(q).u;A.setState(s);return A.getState();});await page.click('[data-destination="surface"]');const landing=await page.evaluate(()=>{const s=SphereApp.getState();return {solid:!SphereCollection.missing(SphereMath.norm(s.position),s),altitude:s.radius-SphereMath.length(s.position),rim:SphereWorld.nearestRim(SphereMath.norm(s.position),s).distance,geometry:SphereSites.geometry(s).map(m=>m.name)};});assert(landing.solid&&Math.abs(landing.altitude-3)<.000001&&landing.rim<3.01);assert(landing.geometry.includes('Wound · fractured shell edge'));await page.click('#seeSurface');const returned=await page.evaluate(()=>SphereApp.getState());assert.deepEqual(returned.position,surfaceStart.position);assert.equal(returned.atmosphere,surfaceStart.atmosphere);
 const overview=await page.evaluate(async()=>{SphereSurface.resetReturn();SphereEvolution.restore();SphereCollectionUI.view('vista');const A=SphereApp,s=A.getState();await A.renderer.prepare(s);A.renderer.draw(s,1600,1000,{exportFrame:true});return A.renderer.canvas.toDataURL('image/png');});fs.writeFileSync(path.join(dir,'designed-shell.png'),Buffer.from(overview.split(',')[1],'base64'));
 fs.writeFileSync(path.join(dir,'verification.json'),JSON.stringify({geo,captures,walking,clouds,panorama,woundAir,landing,errors},null,2));assert.equal(geo.mismatch,0);assert(geo.maxBlend<.004);assert.deepEqual(errors,[]);console.log('PASS all field sites, three Shade damage sections, both entry courts, three exteriors, exact geography, walking restore, keyboard controls, panorama, contained weather and selected Wound landing/return');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
