require('node:fs').mkdirSync(require('node:path').join(__dirname,'artifacts'),{recursive:true});
const {chromium}=require(process.env.SPHERE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),output=process.env.SPHERE_TEST_OUTPUT||path.join(__dirname,'artifacts');fs.mkdirSync(output,{recursive:true});let browser;
(async()=>{
 browser=await chromium.launch({headless:true,...(process.env.SPHERE_BROWSER?{executablePath:process.env.SPHERE_BROWSER}:{})});const page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(root,'index.html')).href);await page.waitForFunction(()=>!!window.SphereEnhancements);
 const rough=await page.evaluate(()=>{const M=SphereMath,r=SphereApp.renderer,w=241,h=137;let total=0,misses=0;for(const amount of [.5,1]){SphereApp.preset('breach',{stage:true});const s=SphereApp.getState();s.breachRoughness=amount;r.draw({...s,viewMode:'objectid'},w,h);const px=new Uint8Array(w*h*4);r.gl.readPixels(0,0,w,h,r.gl.RGBA,r.gl.UNSIGNED_BYTE,px);const b=M.basis(s.forward,s.up),ids={'Inner surface':0,Shade:1,Star:2,'Open space':3};for(let y=0;y<h;y++)for(let x=0;x<w;x++){const d=M.ray((x+.5)/w*2-1,(y+.5)/h*2-1,w/h,s.fov,b);if(ids[M.trace(s.position,d,s).kind]!==Math.round(px[(y*w+x)*4]/85))misses++;total++;}}return {total,misses};});assert.ok(rough.misses<3,JSON.stringify(rough));console.log('PASS fractured-edge GPU / CPU',rough);
 await page.click('[data-preset="interior"]');await page.click('#measureButton');await page.mouse.move(800,400);await page.mouse.down();await page.mouse.move(1100,650,{steps:8});await page.mouse.up();await page.waitForFunction(()=>!!SphereEnhancements.getMeasurement());const box=await page.evaluate(()=>SphereEnhancements.getMeasurement());assert.ok(box.earths>1e6);const dl=page.waitForEvent('download');await page.click('#exportSurvey');const download=await dl;await download.saveAs(path.join(output,'measurement.json'));assert.equal(JSON.parse(fs.readFileSync(path.join(output,'measurement.json'))).area,box.area);
 await page.selectOption('#surveyShape','lasso');await page.mouse.move(800,400);await page.mouse.down();for(const [x,y] of [[1100,400],[1100,650],[800,400]])await page.mouse.move(x,y,{steps:10});await page.mouse.up();await page.waitForFunction(()=>!!SphereEnhancements.getMeasurement());const lasso=await page.evaluate(()=>SphereEnhancements.getMeasurement());assert.ok(lasso.area>box.area*.4&&lasso.area<box.area*.7);console.log('PASS rectangle, freehand, measured JSON export');
 await page.click('[data-preset="dawn"]');await page.waitForTimeout(700);assert.equal(await page.evaluate(()=>SphereEnhancements.getMeasurement()),null);await page.click('#measureButton');
 const anchor=await page.evaluate(()=>{const M=SphereMath,r=SphereApp.renderer,s=M.defaultState();s.shadeEnabled=false;s.breachEnabled=false;s.position=[0,0,s.radius-1];s.forward=[0,0,1];const pixels=[];for(const dx of [0,.001]){s.position=[dx,0,s.radius-1];s.forward=M.norm([-dx,0,1]);r.draw(s,1001,501);const a=new Uint8Array(4);r.gl.readPixels(500,250,1,1,r.gl.RGBA,r.gl.UNSIGNED_BYTE,a);pixels.push([...a]);}return pixels;});assert.ok(anchor[0].every((v,i)=>Math.abs(v-anchor[1][i])<=3),JSON.stringify(anchor));console.log('PASS metre-scale camera rebase preserves sampled material',anchor);
 for(const alt of [1,300]){await page.evaluate(alt=>{const s=SphereMath.defaultState();s.position=[0,0,s.radius-alt];s.forward=[0,0,1];s.shadeEnabled=false;s.breachEnabled=false;SphereApp.setState(s);},alt);await page.waitForTimeout(700);await page.screenshot({path:path.join(output,'surface-'+alt+'km.png')});}
 await page.click('[data-preset="interior"]');await page.click('[data-tab="photo"]');const before=await page.evaluate(()=>SphereApp.getState());const clip=await page.evaluate(async()=>{const {blob,metadata,extension}=await SphereEnhancements.recordClip({shot:'dawn',width:1280,seconds:2,returnBlob:true});const v=document.createElement('video');v.src=URL.createObjectURL(blob);await new Promise((res,rej)=>{v.onloadedmetadata=res;v.onerror=rej;});return {width:v.videoWidth,height:v.videoHeight,duration:v.duration,size:blob.size,metadata,extension};});assert.equal(clip.width,1280);assert.equal(clip.height,720);assert.ok(clip.duration>1.8&&clip.duration<3);assert.deepEqual(await page.evaluate(()=>SphereApp.getState()),before);assert.equal(await page.locator('#viewTitle').textContent(),'The interior');assert.equal(await page.locator('#recordClip').isEnabled(),true);console.log('PASS SDR recording, playback metadata, camera and title restoration', {width:clip.width,height:clip.height,duration:clip.duration,extension:clip.extension});
 assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>SphereApp.renderer.error()),0);fs.writeFileSync(path.join(output,'v02-report.json'),JSON.stringify({rough,anchor,boxAreaKm2:box.area,lassoAreaKm2:lasso.area,clip,errors},null,2));await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exit(1)});
