const {chromium}=require(process.env.SPHERE_PLAYWRIGHT||'playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.SPHERE_BROWSER?{executablePath:process.env.SPHERE_BROWSER}:{})});try{
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto(process.env.SPHERE_URL||'http://127.0.0.1:8766/',{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>!!window.SphereEvolution,{timeout:120000});await page.evaluate(()=>SphereApp.setBusy(true));
 // Exercise ordinary exploration before any capture calls prepare(), which
 // would otherwise hide missing live texture requests on wreckage surfaces.
 const assets=await page.evaluate(async()=>{SphereEvolution.visit('exterior-0');const A=SphereApp,R=A.renderer,s=A.getState(),needed=[0,3,4,5,7];for(let i=0;i<300;i++){R.draw(s,480,270);if(needed.every(id=>R.heroes.status[id]==='ready'))break;await new Promise(resolve=>setTimeout(resolve,20));}return {status:needed.map(id=>R.heroes.status[id]),gl:R.error()};});assert(assets.status.every(s=>s==='ready'));assert.equal(assets.gl,0);console.log('Live exterior textures',assets);
 const dir=path.resolve('work/screenshots/focus-weather');fs.mkdirSync(dir,{recursive:true});const captures=[];
 for(const [name,id,alt,tilt,coverage] of [['forest-below',0,.25,.18,.68],['jungle-within',1,2.6,.05,.68],['jungle-above',1,7,-.20,.68],['ruin-ash',4,3,-.012,.55],['spore-bank',8,.03,.06,.65]]){
  const r=await page.evaluate(async({name,id,alt,tilt,coverage})=>{SphereEvolution.visit('biome-'+id);const A=SphereApp,M=SphereMath,R=A.renderer,s=A.getState(),frame=SphereSites.shellFrame(s.siteAnchor);s.position=M.mul(s.siteAnchor,s.radius-alt);s.forward=M.norm(M.add(frame[2],M.mul(frame[1],tilt)));s.up=M.basis(s.forward,frame[1]).u;s.fov=85;s.routeShades=false;s.atmosphere=1;s.weatherStrength=coverage;s.weatherQuality=2;s.cavityHaze=.28;A.setState(s);await R.prepare(s);R.draw(s,1440,900,{exportFrame:true});return {name,state:s,info:R.renderInfo,gl:R.error(),image:R.canvas.toDataURL('image/png')};},{name,id,alt,tilt,coverage});fs.writeFileSync(path.join(dir,name+'.png'),Buffer.from(r.image.split(',')[1],'base64'));delete r.image;captures.push(r);assert.equal(r.gl,0);console.log(name,r.info.volume);
 }
 const weather=await page.evaluate(()=>{const A=SphereApp,M=SphereMath,R=A.renderer,gl=R.gl;SphereEvolution.visit('biome-1');const s=A.getState(),f=SphereSites.shellFrame(s.siteAnchor);s.position=M.mul(s.siteAnchor,s.radius-2.5);s.forward=f[2];s.up=f[1];s.geometryDetail=false;s.routeShades=false;s.antialias=0;s.atmosphere=1;s.weatherStrength=.8;s.cavityHaze=0;const w=240,h=160,read=()=>{const p=new Uint8Array(w*h*4);gl.readPixels(0,0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,p);return p;},difference=(a,b)=>a.reduce((sum,v,i)=>sum+(i%4===3?0:Math.abs(v-b[i])),0);
  R.draw({...s,clouds:false},w,h);const clear=read();R.draw({...s,clouds:true,weatherQuality:2},w,h);const cloud=read();R.draw({...s,clouds:true,weatherQuality:2},w,h);const repeat=read();R.draw({...s,clouds:true,weatherQuality:0},w,h);const low=read();R.draw({...s,time:s.time+600,clouds:true,weatherQuality:2},w,h);const moved=read();
  const record=M.validate(M.sceneRecord({...s,weatherQuality:2,cavityHaze:.63}).state);return {cloudDifference:difference(clear,cloud),repeatDifference:difference(cloud,repeat),qualityDifference:difference(cloud,low),windDifference:difference(cloud,moved),restored:[record.weatherQuality,record.cavityHaze],gl:R.error()};});console.log('Weather',weather);assert.equal(weather.gl,0);assert(weather.cloudDifference>1000);assert.equal(weather.repeatDifference,0);assert(weather.windDifference>1000);assert.deepEqual(weather.restored,[2,.63]);
 const light=await page.evaluate(()=>{const A=SphereApp,M=SphereMath,C=SphereCollection,R=A.renderer,gl=R.gl,w=24,h=16;let rays=0,mismatch=0,outOfBound=0,maxError=0,partial=0,lit=0,shadow=0;const failures=[];
  for(const axisLat of [-40,63])for(const waistWidth of [10,38])for(const shape of ['disk','square','cap','trimmed'])for(const band of [0,1,2]){const s={...A.getState(),axisLat,waistWidth,shadeShape:shape,era:'before',routeShades:true,starStation:false,shadowSamples:19,geometryDetail:false,antialias:0,viewMode:'surfaceLight',time:band*81371},p=C.plates(s).find(p=>p.band===band),q=M.norm(M.add(p.center,M.mul(p.right,p.size*p.across*(shape==='trimmed'?s.shadeTrim:1))));s.position=M.mul(q,s.radius*.997);s.forward=q;s.up=p.right;s.fov=110;R.draw(s,w,h);const px=new Uint8Array(w*h*4);gl.readPixels(0,0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,px);const frame=M.basis(s.forward,s.up);
   for(let y=0;y<h;y++)for(let x=0;x<w;x++){const d=M.ray((x+.5)/w*2-1,(y+.5)/h*2-1,w/h,s.fov,frame),hit=M.trace(s.position,d,s);if(hit.kind!=='Inner surface')continue;const cpu=C.visibility(hit.point,s,19),gpu=px[(y*w+x)*4]/255,error=Math.abs(cpu-gpu);maxError=Math.max(maxError,error);if(error>1/19+1/255)outOfBound++;rays++;if(cpu===0)shadow++;else if(cpu===1)lit++;else partial++;if(Math.abs(cpu-gpu)>.01){mismatch++;if(failures.length<5)failures.push({shape,axisLat,waistWidth,band,x,y,cpu,gpu});}}
  }return {rays,mismatch,outOfBound,maxError,partial,lit,shadow,failures,gl:R.error()};});console.log('Aligned fleet light',light);assert.equal(light.gl,0);assert.equal(light.outOfBound,0);assert(light.mismatch/light.rays<.001);assert(light.partial&&light.lit&&light.shadow);
 const collision=[];
 for(const hole of [false,true]){await page.evaluate(hole=>{const A=SphereApp,M=SphereMath,s=A.getState(),q=hole?SphereCollection.wounds[0].axis:SphereWorld.frame(s).axis;s.position=M.mul(q,s.radius-1);s.forward=q;s.up=M.basis(q).u;s.speed=100;s.siteId='';s.siteAnchor=null;s.walkMode=false;s.walkPosition=null;s.geometryDetail=false;s.playing=false;s.era='after';s.multipleWounds=hole;s.routeShades=false;A.setState(s);A.setBusy(false);},hole);await page.locator('#viewport').focus();await page.keyboard.down('w');await page.waitForTimeout(450);await page.keyboard.up('w');const r=await page.evaluate(()=>{SphereApp.setBusy(true);const s=SphereApp.getState();return {altitude:s.radius-SphereMath.length(s.position),gl:SphereApp.renderer.error()};});collision.push({hole,...r});assert.equal(r.gl,0);if(hole)assert(r.altitude<-.1);else assert(Math.abs(r.altitude-.002)<.000003);}
 console.log('Keyboard collision',collision);
 const depth=await page.evaluate(()=>{const A=SphereApp,M=SphereMath,R=A.renderer,gl=R.gl;SphereCollectionUI.view('vista',{stage:true});const s={...A.getState(),geometryDetail:false,antialias:0,routeShades:true,atmosphere:0},w=180,h=120,read=()=>{const px=new Uint8Array(w*h*4);gl.readPixels(0,0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,px);return px;};R.draw({...s,cavityHaze:0},w,h);const clear=read();R.draw({...s,cavityHaze:.6},w,h);const hazy=read();const difference=clear.reduce((sum,v,i)=>sum+Math.abs(v-hazy[i]),0);s.position=M.mul(M.norm(s.position),s.radius*1.1);s.forward=M.norm(s.position);s.up=M.basis(s.forward).u;s.fov=60;R.draw({...s,cavityHaze:0},w,h);const space=read();R.draw({...s,cavityHaze:1},w,h);const dusty=read();return {difference,spaceDifference:space.reduce((sum,v,i)=>sum+Math.abs(v-dusty[i]),0),gl:R.error()};});console.log('Depth cues',depth);assert(depth.difference>1000);assert.equal(depth.spaceDifference,0);assert.equal(depth.gl,0);
 const performance=[];for(const quality of [0,1,2]){const r=await page.evaluate(async quality=>{const A=SphereApp,M=SphereMath,R=A.renderer;SphereEvolution.visit('biome-1');const s=A.getState(),f=SphereSites.shellFrame(s.siteAnchor);s.position=M.mul(s.siteAnchor,s.radius-2.6);s.forward=f[2];s.up=f[1];s.routeShades=false;s.weatherQuality=quality;s.weatherStrength=.8;s.atmosphere=1;s.antialias=3;const times=[];for(let i=0;i<16;i++){R.draw(s,1280,720);await new Promise(resolve=>setTimeout(resolve,24));R.pollTimers();if(i>4&&R.gpuMs!=null)times.push(R.gpuMs);}times.sort((a,b)=>a-b);return {quality,gpuMedianMs:times[Math.floor(times.length/2)],gpuMaxMs:times.at(-1),info:R.renderInfo,device:R.device,gl:R.error()};},quality);performance.push(r);assert.equal(r.gl,0);console.log('Preview GPU',r);}
 const bounce=await page.evaluate(async()=>{const A=SphereApp,C=SphereCollection,R=A.renderer,s={...A.getState(),playing:true,shineField:true};let calls=0;const original=C.cavity;C.cavity=(...args)=>{calls++;return original(...args);};try{for(let i=0;i<12;i++){s.time+=1;R.draw(s,320,180);await new Promise(resolve=>setTimeout(resolve,20));}return {calls,finiteFill:R.frameFill.every(Number.isFinite),gl:R.error()};}finally{C.cavity=original;}});assert(bounce.calls<=1);assert(bounce.finiteFill);assert.equal(bounce.gl,0);console.log('Live bounce remains asynchronous',bounce);
 fs.writeFileSync(path.join(dir,'verification.json'),JSON.stringify({application:'The Sphere Observatory 1.1',assets,captures,weather,light,collision,depth,performance,bounce,errors},null,2));assert.deepEqual(errors,[]);console.log('PASS focused graphics, volume controls, deterministic captures, wind, fleet penumbrae, collision controls and vacuum preservation');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
