const assert=require('node:assert/strict'),M=require('../math.js');for(const f of ['collection','biomes','world-palette','world','field-sites','flight','surface-walk'])require('../'+f+'.js');
const G=SphereGround,S=SphereSites,E=SphereEdges,W=SphereWorld,s={...M.defaultState(),collection:true,routeShades:false,starStation:false,multipleWounds:false,siteId:'biome-2',siteRevision:2,walkMode:false};s.siteAnchor=W.locateBiome(2,s);const f=G.frame(s);s.position=f.world([.4,.1,.4]);
assert.equal(M.validate({...M.defaultState(),terrainRevision:undefined}).terrainRevision,1,'Old scenes keep their height generator');
let joins=0;const visited=new Map(),times=[];for(const x of [...Array.from({length:12},(_,i)=>i+.4),...Array.from({length:12},(_,i)=>Number((11.4-i).toFixed(1)))]){s.position=f.world([x,.1,.4]);const start=performance.now(),groups=G.neighbourhood(s);times.push(performance.now()-start);assert.equal(groups.length,25);assert(G.info.bytes<=G.info.budget);const floor=G.ground(s,x,.4);assert(Number.isFinite(floor));
 const address=x.toFixed(1),value={floor,props:groups.filter(m=>m.chunk.cells===64).flatMap(m=>m.ground.props).sort()};if(visited.has(address))assert.deepEqual(value,visited.get(address),'Returning cannot reroll terrain or objects');else visited.set(address,value);
 const current=groups.find(m=>m.chunk.x===Math.floor(x/G.SIZE)&&m.chunk.z===0),next=groups.find(m=>m.chunk.x===current.chunk.x+1&&m.chunk.z===0),border=(current.chunk.x+1)*G.SIZE;
 const edge=m=>{const points=new Set();for(let i=0;i<m.vertices.length;i+=11)if(m.vertices[i]===Math.fround(border)&&m.vertices[i+9]>=0)points.add([m.vertices[i],m.vertices[i+1],m.vertices[i+2]].join(','));return points;},a=edge(current),b=edge(next);for(const p of a)assert(b.has(p),'Adjacent chunks share exact uploaded border vertices');joins++;
}
// Actual controller crosses a join without the former 1.08 km clamp.
s.position=f.world([1.078,.1,.4]);SphereLanding.enter(s,s.position);for(let i=0;i<150;i++)S.step(s,new Set(),1/60);s.forward=f.basis[0];s.up=f.basis[1];for(let i=0;i<200;i++)S.step(s,new Set(['KeyW']),1/60);assert(s.walkPosition[0]>1.08);M.validate(s);
// Clipped fine/coarse chunks at a real Wound use one coalesced complement.
const w={...s,walkMode:false,terrainAnchor:null,multipleWounds:true,siteId:'biome-5'},rim=W.rimFrame(w,0,Math.PI/2);w.siteAnchor=M.norm(M.add(rim.point,M.mul(rim.inland,.02/w.radius)));w.position=M.mul(w.siteAnchor,w.radius-.04);const groups=G.neighbourhood(w),cut=G.rimCut(w);assert(cut&&cut.ends.length===2);for(const mesh of groups)for(const seg of mesh.ground.rim?.segments||[]){for(const p of [seg.a,seg.b])assert(Math.abs(SphereCollection.woundDistance(M.norm(mesh.world(p)),SphereCollection.wounds[0])-1)<1e-10);}
console.log(JSON.stringify({status:'PASS',joins,residency:G.info,syncBuildMs:{max:Math.max(...times)}}));
