const {chromium}=require(process.env.SPHERE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.SPHERE_BROWSER||'C:/Program Files/Google/Chrome/Application/chrome.exe'}),errors=[],results=[],dir='work/integration';fs.mkdirSync(dir,{recursive:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:900},acceptDownloads:true});page.setDefaultTimeout(180000);page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});
 await page.goto(process.env.SPHERE_URL||'http://127.0.0.1:8766/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.SphereLoading?.ready);console.log('Ready with real loop');
 const ready=()=>page.waitForFunction(()=>!SphereJourney.travel.active&&!SphereApp.travelHeld&&SphereJourney.travel.status.state==='arrived');
 const visit=async(category,id,arrival)=>{await page.locator('[data-tab=camera]').click();await page.locator('[data-category='+category+']').click();await page.locator('#placeDestination').selectOption(id);await page.locator('#placeAltitude').selectOption(arrival);const start=Date.now();await page.locator('#visitPlace').click();await ready();results.push({id,arrival,ms:Date.now()-start});console.log('Arrived',id,arrival,Date.now()-start);};
 await visit('biomes','biome-0','ground');await page.waitForTimeout(3200);assert.match(await page.locator('#locationName').textContent(),/forest/i);const forest=await page.evaluate(()=>({state:SphereApp.getState(),count:SphereJourney.count}));
 // A mark remains anchored through an actual drag and resize, and Go uses it.
 const canvas=await page.locator('#view').boundingBox();await page.mouse.click(canvas.x+canvas.width*.67,canvas.y+canvas.height*.68);const mark=await page.evaluate(()=>SpherePlaceBrowser.picked);assert(mark);await page.mouse.move(canvas.x+canvas.width*.4,canvas.y+canvas.height*.4);await page.mouse.down();await page.mouse.move(canvas.x+canvas.width*.46,canvas.y+canvas.height*.42,{steps:8});await page.mouse.up();await page.setViewportSize({width:1380,height:900});await page.waitForTimeout(300);assert.deepEqual(await page.evaluate(()=>SpherePlaceBrowser.picked),mark);await page.locator('#seeSurface').click();await ready();const arrived=await page.evaluate(()=>SphereApp.getState().position);if(mark.type==='geometry')assert(Math.hypot(...arrived.map((v,i)=>v-mark.point[i]-mark.normal[i]*mark.standOff))<.00001,'Go keeps the originally marked geometry address');
 await visit('watersheds','watershed-lake','ground');assert.match(await page.locator('#locationName').textContent(),/Receiving lake/);assert.equal(await page.locator('#captureTitle').inputValue(),'Receiving lake');
 // Failed Return keeps state and entry; retry commits once.
 const previous=await page.evaluate(()=>({state:SphereApp.getState(),entries:SphereJourney.entries}));
 await page.evaluate(()=>{const R=SphereApp.renderer,prepare=R.prepare;R.prepare=async function(...args){R.prepare=prepare;throw Error('Injected Return failure');};});await page.locator('#browseBiomes').click();await page.waitForFunction(()=>SphereJourney.travel.status.state==='failed'&&!SphereJourney.travel.active);assert.equal(await page.evaluate(()=>SphereJourney.count),previous.entries.length);assert.equal(await page.evaluate(()=>SphereApp.getState().siteId),previous.state.siteId);await page.locator('#retryTravel').click();await ready();assert.equal(await page.evaluate(()=>SphereJourney.count),previous.entries.length-1);console.log('Failed Return and retry retained history');
 await visit('shades','shade-0','ground');const shade=await page.evaluate(()=>({speed:SphereTravel.estimate(SphereApp.getState()),position:SphereApp.getState().position}));assert(shade.speed<1);await page.locator('#play').click();await page.waitForTimeout(500);assert.notDeepEqual(await page.evaluate(()=>SphereApp.getState().position),shade.position);
 await page.evaluate(()=>{const R=SphereApp.renderer,prepare=R.prepare;R.prepare=async function(...args){R.prepare=prepare;await new Promise(r=>setTimeout(r,500));return prepare.apply(R,args);};});await visit('biomes','biome-3','clouds');await page.locator('#browseBiomes').click();await ready();assert.equal(await page.evaluate(()=>SphereApp.getState().shadeAttachment),0);
 // Browsing the draft and live settings do not cancel or redirect a submitted trip.
 await page.evaluate(()=>{const R=SphereApp.renderer,prepare=R.prepare;R.prepare=async function(...args){R.prepare=prepare;await new Promise(r=>setTimeout(r,1200));return prepare.apply(R,args);};});
 await page.locator('[data-category=biomes]').click();await page.locator('#placeDestination').selectOption('biome-0');await page.locator('#placeAltitude').selectOption('clouds');await page.locator('#visitPlace').click();await page.waitForFunction(()=>SphereJourney.travel.active);await page.locator('#placeDestination').selectOption('biome-3');await page.evaluate(()=>{const s=SphereApp.getState();s.exposure=1.7;s.quality=.5;s.autoSpeed=false;s.speed=.3;SphereApp.setState(s);SphereApp.setPlaying(false);});await ready();const latest=await page.evaluate(()=>SphereApp.getState());assert.equal(latest.exposure,1.7);assert.equal(latest.quality,.5);assert.equal(latest.speed,.3);assert.equal(latest.playing,false);assert.match(await page.locator('#locationName').textContent(),/forest/i);
 // Explicit era change cancels incompatible work and explains unavailable routes.
 await page.evaluate(()=>{const R=SphereApp.renderer,prepare=R.prepare;R.prepare=async function(...args){R.prepare=prepare;await new Promise(r=>setTimeout(r,1200));return prepare.apply(R,args);};});await page.locator('#visitPlace').click();await page.waitForFunction(()=>SphereJourney.travel.active);await page.locator('#eraBefore').click();await page.waitForFunction(()=>SphereJourney.travel.status.state==='cancelled'&&!SphereJourney.travel.active);await page.locator('[data-category=wounds]').click();assert(await page.locator('#visitPlace').isDisabled());assert.match(await page.locator('#placeAvailability').textContent(),/after the attack/i);await page.locator('#eraAfter').click();
 for(const arrival of ['neighbourhood','region','province','approach','garden','terrace','ground'])await visit('watersheds','watershed',arrival);
 assert.equal(await page.evaluate(()=>SphereApp.getState().walkMode),true);
 await page.evaluate(()=>SphereSession.flush());const savedCount=await page.evaluate(()=>SphereJourney.count);await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.SphereLoading?.ready);assert.equal(await page.evaluate(()=>SphereApp.getState().playing),false);assert.equal(await page.evaluate(()=>SphereJourney.count),savedCount);assert(await page.locator('#browseBiomes').isEnabled());console.log('Journey survives reload');
 for(const [width,height]of [[1440,900],[1024,768],[390,844],[844,390]]){await page.setViewportSize({width,height});await page.locator('[data-tab=camera]').click();await page.waitForTimeout(200);await page.screenshot({path:dir+'/'+width+'x'+height+'.png'});assert(await page.locator('#visitPlace').isVisible());assert(await page.locator('#browseBiomes').isVisible());const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert(!overflow,'No horizontal overflow '+width);if(width<760||height<500){await page.locator('#closeToolPanel').click();assert(await page.locator('#togglePanel').isVisible());await page.locator('#togglePanel').click();assert(await page.locator('#visitPlace').isVisible());}}
 await page.setViewportSize({width:1440,height:900});await page.locator('[data-tab=photo]').click();await page.evaluate(()=>{const R=SphereApp.renderer,prepare=R.prepare;R.prepare=async function(...args){R.prepare=prepare;await new Promise(r=>setTimeout(r,700));return prepare.apply(R,args);};});await page.locator('#capture').click();await page.locator('#cancelPhoto').click();await page.waitForFunction(()=>!SphereApp.busy);assert.match(await page.locator('#captureStatus').textContent(),/cancelled/i);
 await page.evaluate(()=>{const R=SphereApp.renderer,prepare=R.prepare;R.prepare=async function(){R.prepare=prepare;throw Error('Injected capture failure');};});await page.locator('#capture').click();await page.waitForFunction(()=>!SphereApp.busy);assert.match(await page.locator('#captureStatus').textContent(),/Injected capture failure/);assert.equal(await page.evaluate(()=>SphereApp.getState().playing),false);
 assert.deepEqual(errors,[]);const diagnostic=await page.evaluate(()=>({device:SphereApp.renderer.device,timing:SphereTiming.diagnostics,ground:SphereGround.info,build:window.SphereBuild,history:SphereJourney.count}));fs.writeFileSync(dir+'/browser-results.json',JSON.stringify({results,errors,diagnostic},null,2));console.log('PASS visible journey, marks, six scales, Return failure/retry, live settings, era cancellation, reload, responsive layouts, capture cancellation/failure');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
