const {chromium}=require(process.env.SPHERE_PLAYWRIGHT||'playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.SPHERE_BROWSER?{executablePath:process.env.SPHERE_BROWSER}:{})});try{
 const page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});page.on('console',m=>{if(m.type()==='error'){errors.push(m.text());console.error(m.text());}});page.setDefaultTimeout(120000);
 await page.goto(process.env.SPHERE_URL||'http://127.0.0.1:8766/',{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.SphereEvolution);await page.evaluate(()=>SphereApp.setBusy(true));
 const dir=path.resolve('work/screenshots/materials');fs.mkdirSync(dir,{recursive:true});const captures=[];
 for(const id of ['shade-0','rim','shade-under','rim-grazing','rim-close']){
  const r=await page.evaluate(async id=>{const A=SphereApp,M=SphereMath,R=A.renderer;SphereEvolution.visit(id.startsWith('rim')?'rim':'shade-0');const s=A.getState();s.antialias=2;s.atmosphere=0;s.cavityHaze=0;
   if(id==='shade-under'){const f=SphereSites.shadeSection(s);s.position=f.world([-.23,-.18,.34]);s.forward=M.norm(M.sub(f.world([.3,-.04,0]),s.position));s.up=f.basis[1];s.exposure=1.;}
   if(id==='rim-grazing'){const f=SphereWorld.rimFrame(s);s.position=M.add(M.mul(f.point,s.radius-.5),M.mul(f.inland,-.8));s.forward=M.norm(M.add(M.add(f.tangent,M.mul(f.inland,.18)),M.mul(f.point,.08)));s.up=M.mul(f.point,-1);s.fov=78;}
   if(id==='rim-close'){const f=SphereWorld.rimFrame(s),edge=SphereEdges.rimPoint(s,0,Math.PI/2,2.3);s.position=M.add(edge,M.mul(f.inland,-.16));s.forward=M.norm(M.add(f.inland,M.mul(f.tangent,.45)));s.up=M.mul(f.point,-1);s.fov=76;s.exposure=2.;}
   await R.prepare(s);const w=1280,h=800,gl=R.gl,read=()=>{const px=new Uint8Array(w*h*4);gl.readPixels(0,0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,px);return px;},difference=(a,b)=>{let sum=0,changed=0,brighter=0;for(let i=0;i<a.length;i+=4){let d=0;for(let j=0;j<3;j++)d+=a[i+j]-b[i+j];sum+=Math.abs(d);if(Math.abs(d)>6)changed++;if(d< -6)brighter++;}return {mean:sum/(w*h*3),changed,brighter};};
   R.draw({...s,richMaterials:false,localShadows:0},w,h,{exportFrame:true});const old=read(),before=R.canvas.toDataURL('image/png');
   R.draw({...s,richMaterials:true,localShadows:0},w,h,{exportFrame:true});const material=read();
   R.draw({...s,richMaterials:true,localShadows:2},w,h,{exportFrame:true});const shaded=read(),after=R.canvas.toDataURL('image/png'),info=structuredClone(R.renderInfo);
   R.draw({...s,richMaterials:true,localShadows:2},w,h,{exportFrame:true});const repeated=read();
   return {id,state:s,before,after,info,materials:difference(old,material),shadows:difference(material,shaded),repeat:difference(shaded,repeated),gl:R.error()};
  },id);for(const key of ['before','after']){fs.writeFileSync(path.join(dir,id+'-'+key+'.png'),Buffer.from(r[key].split(',')[1],'base64'));delete r[key];}captures.push(r);console.log(JSON.stringify(r));assert.equal(r.gl,0);assert.equal(r.repeat.mean,0);assert(r.materials.changed>200);assert.equal(r.shadows.brighter,0);assert(r.info.structureShadows.enabled);
 }
 assert(captures.some(r=>r.shadows.changed>500),'Structures must visibly shadow other surfaces');
 const fixture=await page.evaluate(()=>{const A=SphereApp,M=SphereMath,S=SphereSites,R=A.renderer,gl=R.gl,s={...A.getState(),siteId:'',siteAnchor:null,atmosphere:0,cavityHaze:0,routeShades:false,starStation:false,multipleWounds:false,shellshine:.04,shineField:false,exposure:0,antialias:0,richMaterials:false},origin=[0,0,s.radius-1],mesh=new S.Mesh(origin,[[1,0,0],[0,0,-1],[0,1,0]],'shadow test');
  mesh.quad([-.6,0,-.6],[.6,0,-.6],[.6,0,.6],[-.6,0,.6],[.25,.25,.25]);mesh.box([0,.10,0],[.2,.02,.2],[.18,.18,.18]);mesh.finish();s.position=mesh.world([.4,.2,.3]);s.forward=M.norm(M.sub(mesh.world([0,0,0]),s.position));s.up=mesh.basis[1];s.fov=70;
  const original=S.geometry;S.geometry=()=>[mesh];try{const w=256,h=192,read=()=>{const p=new Uint8Array(w*h*4);gl.readPixels(0,0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,p);return p;};R.draw({...s,localShadows:0},w,h,{exportFrame:true});const before=read();R.draw({...s,localShadows:2},w,h,{exportFrame:true});const after=read();const b=M.basis(s.forward,s.up),p=mesh.local(s.position);let shadowed=0,lit=0,wrong=0;
   for(let y=0;y<h;y++)for(let x=0;x<w;x++){const ray=M.ray((x+.5)/w*2-1,(y+.5)/h*2-1,w/h,s.fov,b),d=mesh.basis.map(a=>M.dot(ray,a)),t=-p[1]/d[1];if(t<=0)continue;const q=M.add(p,M.mul(d,t));if(Math.max(Math.abs(q[0]),Math.abs(q[2]))>.5)continue;const hit=S.rayBVH(p,d,mesh.bvh);if(Math.abs(hit-t)>.0001)continue;
    const edge=Math.max(Math.abs(q[0]),Math.abs(q[2]));if(Math.abs(edge-.1)<.012)continue;const j=(y*w+x)*4,dimmed=after[j]<before[j]*.7;if(edge<.1){shadowed++;if(!dimmed)wrong++;}else{lit++;if(Math.abs(after[j]-before[j])>3)wrong++;}
   }
   // Exactly opposed view and light directions must not normalize a zero halfway vector.
   mesh.name='Wound · backlit fixture';R.draw({...s,localShadows:2,richMaterials:true,position:mesh.world([0,-.1,0]),forward:mesh.basis[1],up:mesh.basis[2]},w,h,{exportFrame:true});gl.bindFramebuffer(gl.FRAMEBUFFER,R.lightBuffer);const linear=new Float32Array(w*h*4);gl.readPixels(0,0,w,h,gl.RGBA,gl.FLOAT,linear);gl.bindFramebuffer(gl.FRAMEBUFFER,null);
   return {shadowed,lit,wrong,finiteBacklit:linear.every(Number.isFinite),gl:R.error()};
  }finally{S.geometry=original;}
 });console.log('Known caster/receiver',fixture);assert.equal(fixture.gl,0);assert(fixture.finiteBacklit);assert(fixture.shadowed>100&&fixture.lit>1000);assert.equal(fixture.wrong,0,'Shadows must agree with an independent geometric fixture away from its soft edge');
 const performances=[];
 for(const id of ['shade-0','rim'])for(const quality of [0,1,2]){const r=await page.evaluate(async({id,quality})=>{const A=SphereApp,R=A.renderer;SphereEvolution.visit(id);const s=A.getState();s.localShadows=quality;s.richMaterials=true;s.antialias=3;const times=[];for(let j=0;j<24;j++){SphereInspection.setTime(s,s.time+.01);R.draw(s,1280,720);await new Promise(resolve=>setTimeout(resolve,25));R.pollTimers();if(j>9&&R.gpuMs!=null)times.push(R.gpuMs);}times.sort((a,b)=>a-b);return {id,quality,gpuMedian:times[Math.floor(times.length/2)],gpuMax:times.at(-1),info:R.renderInfo,device:R.device,gl:R.error()};},{id,quality});performances.push(r);assert.equal(r.gl,0);console.log('GPU',JSON.stringify(r));}
 const controls=await page.evaluate(()=>{const A=SphereApp;const set=(id,value)=>{const e=document.getElementById(id);if(e.type==='checkbox')e.checked=value;else e.value=String(value);e.dispatchEvent(new Event('change',{bubbles:true}));};set('localShadows',2);set('richMaterials',false);const s=SphereMath.validate(A.record().state);return {localShadows:s.localShadows,richMaterials:s.richMaterials};});assert.deepEqual(controls,{localShadows:2,richMaterials:false});
 fs.writeFileSync(path.join(dir,'verification.json'),JSON.stringify({captures,fixture,performances,controls,errors},null,2));assert.deepEqual(errors,[]);console.log('PASS deterministic materials, known caster/receiver shadows, controls, scene restoration and preview GPU timing.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
