const {chromium}=require(process.env.SPHERE_PLAYWRIGHT),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.SPHERE_BROWSER});try{const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true}),errors=[];page.setDefaultTimeout(180000);page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8766/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.SphereLoading?.ready);await page.evaluate(()=>{const M=SphereMath,s={...M.defaultState(),collection:true,routeShades:false,geometryDetail:false,clouds:false,atmosphere:0,cavityHaze:0},q=SphereWorld.locateBiome(2,s);s.position=M.mul(q,s.radius-100);s.forward=q;s.up=M.basis(q).u;SphereApp.setState(s);SphereApp.setPlaying(true);});console.log('Measurement ready');
 const box=await page.locator('#view').boundingBox();await page.locator('#measureButton').click();
 async function draw(points){await page.mouse.move(box.x+points[0][0]*box.width,box.y+points[0][1]*box.height);await page.mouse.down();for(const p of points.slice(1))await page.mouse.move(box.x+p[0]*box.width,box.y+p[1]*box.height,{steps:10});await page.mouse.up();await page.waitForFunction(()=>SphereEnhancements.getMeasurement()?.area>0);}
 await draw([[.3,.35],[.67,.68]]);const first=await page.evaluate(()=>({measurement:SphereEnhancements.getMeasurement(),path:document.getElementById('surveyPath').getAttribute('d'),time:SphereApp.getState().time}));
 await page.waitForFunction(t=>SphereApp.getState().time>t+1,first.time);await page.waitForTimeout(1400);
 const kept=await page.evaluate(()=>({area:SphereEnhancements.getMeasurement()?.area,path:document.getElementById('surveyPath').getAttribute('d'),visible:document.getElementById('surveyPath').style.visibility,playing:SphereApp.getState().playing}));assert.equal(kept.area,first.measurement.area);assert.equal(kept.path,first.path);assert.equal(kept.visible,'visible');assert(kept.playing);assert(await page.locator('#exportSurvey').isEnabled());
 await page.locator('#measureButton').click();await page.locator('#measureButton').click();assert.equal(await page.evaluate(()=>SphereEnhancements.getMeasurement().area),first.measurement.area);
 await page.locator('#surveyShape').selectOption('lasso');await draw([[.31,.32],[.62,.34],[.68,.56],[.47,.68],[.3,.52],[.31,.32]]);await page.waitForTimeout(1400);const free=await page.evaluate(()=>SphereEnhancements.getMeasurement());assert(free.area>0&&free.polygon.length>5);
 const download=page.waitForEvent('download');await page.locator('#exportSurvey').click();const saved=JSON.parse(fs.readFileSync(await (await download).path()));assert.equal(saved.area,free.area);assert.equal(saved.state.time,free.state.time);
 await page.locator('[data-destination=overview]').click();assert.equal(await page.evaluate(()=>SphereEnhancements.measuring),false);assert.equal(await page.evaluate(()=>SphereEnhancements.getMeasurement().area),free.area);await page.locator('#measureButton').click();await page.waitForFunction(()=>document.getElementById('surveyPath').style.visibility==='hidden');assert((await page.locator('#surveyResult').textContent()).includes('previous view'));
 await page.locator('#clearSurvey').click();assert.equal(await page.evaluate(()=>SphereEnhancements.getMeasurement()),null);assert.equal(await page.locator('#surveyPath').getAttribute('d'),'');assert(await page.locator('#exportSurvey').isDisabled());assert(await page.evaluate(()=>SphereApp.getState().playing));assert.deepEqual(errors,[]);
 fs.mkdirSync('work/screenshots/places',{recursive:true});fs.writeFileSync('work/screenshots/places/measurement-verification.json',JSON.stringify({rectangle:first.measurement,retained:kept,freehand:free,errors},null,2));console.log('PASS rectangle/freehand persist through clock ticks, tool close/reopen, snapshot export, navigation and explicit Clear');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
