const {chromium}=require(process.env.SPHERE_PLAYWRIGHT||'playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
function unzip(bytes){const out={};let p=0;while(p+30<=bytes.length&&bytes.readUInt32LE(p)===0x04034b50){assert.equal(bytes.readUInt16LE(p+8),0);const size=bytes.readUInt32LE(p+18),n=bytes.readUInt16LE(p+26),extra=bytes.readUInt16LE(p+28),name=bytes.subarray(p+30,p+30+n).toString(),start=p+30+n+extra;out[name]=bytes.subarray(start,start+size);p=start+size;}return out;}
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.SPHERE_BROWSER});try{
 const page=await browser.newPage({viewport:{width:1440,height:960},acceptDownloads:true}),dir=path.resolve('work/screenshots/neighbourhood/verification'),errors=[],start=Date.now();fs.mkdirSync(dir,{recursive:true});page.setDefaultTimeout(240000);page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8766/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.SphereLoading?.ready);const coldStartupMs=Date.now()-start;await page.evaluate(()=>SphereApp.setBusy(true));console.log('Pack audit ready',coldStartupMs);
 const audit=await page.evaluate(async()=>{
  const M=SphereMath,P=SphereWatershed,N=SphereNeighbourhood,R=SphereApp.renderer,gl=R.gl;let s=SpherePacks.activate({...M.defaultState(),collection:true,era:'after',clouds:false,atmosphere:0,cavityHaze:0});const start=performance.now();await P.prepare(s);const coldProvinceMs=performance.now()-start;s=P.view(s,'province');const graph=N.model(s.provinceSeed),ready=performance.now();await R.prepare(s);const uploadMs=performance.now()-ready;
  const source='#version 300 es\nprecision highp float;out vec4 fragColor;uniform float uRadius;float noise(vec3 p){return 0.;}\n'+N.shader.declarations+N.shader.material.replace('return mix(original,land,coverage);','return vec3(water,road,coverage);')+'\nvoid main(){fragColor=vec4(packMaterial(vec3(0.),vec3(0.),.00001),1.);}';
  const program=SphereGLProgram(gl,SphereShaders.vertex,source),fbo=gl.createFramebuffer(),tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,1,1,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.bindFramebuffer(gl.FRAMEBUFFER,fbo);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,tex,0);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('Audit framebuffer unavailable');gl.viewport(0,0,1,1);gl.disable(gl.DEPTH_TEST);gl.useProgram(program.p);gl.uniform1f(program.u.uRadius,s.radius);let probes=0;const failures=[];
  for(const e of graph.edges)for(const offset of [0,.5,1.4]){const t=.37,u=(4+t)/12,a=e.points[4],b=e.points[5],dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz),w=e.widthA*(1-u)+e.widthB*u,x=a[0]+dx*t-dz/len*w*offset,z=a[1]+dz*t+dx/len*w*offset,q=P.direction(x,z,s),state={...s,position:M.mul(q,s.radius-1)};SphereWorld.upload(gl,program.u,state);gl.drawArrays(gl.TRIANGLES,0,3);const pixel=new Uint8Array(4);gl.readPixels(0,0,1,1,gl.RGBA,gl.UNSIGNED_BYTE,pixel);const cpu=N.sampleLocal(x,z,s.provinceSeed);probes++;if((pixel[0]>127)!==cpu.water||Math.abs(pixel[2]/255-cpu.coverage)>.005)failures.push({x,z,pixel:[...pixel],cpu});}
  gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.deleteFramebuffer(fbo);gl.deleteTexture(tex);gl.deleteProgram(program.p);
  const traversal=[];for(const [x,z] of [[1100,400],[1400,550],[1800,700],[2400,1300]]){const q=P.direction(x,z,s),v={...s,position:M.mul(q,s.radius-.16),forward:q,up:M.basis(q).u,autoSpeed:false,speed:.017,playing:true};const target=N.sample(q,v);if(target.water)throw Error('Dry-bank test address became water');const hit=SphereSites.trace(v.position,v.forward,v,M.trace);const moved=SphereLanding.move(v,q,.15);if(!moved.landed)throw Error('Neighbourhood bank did not land');await R.prepare(v);for(let i=0;i<180;i++)SphereSites.step(v,new Set(),1/60);const saved=M.validate(M.sceneRecord(v).state),height=SphereLanding.heightAboveGround(v);traversal.push({x,z,height,hit:hit.kind,playing:v.playing,speed:v.speed,autoSpeed:v.autoSpeed,addressEqual:JSON.stringify(saved.packAddress)===JSON.stringify(s.packAddress)});SphereLanding.release(v);}
  const timings=[],gpu=[],rafPeriods=[];let lastRaf=null;s=P.view(s,'province');s.clouds=false;s.atmosphere=0;s.cavityHaze=0;SphereApp.setState(s);await R.prepare(s);for(let i=0;i<45;i++){const t=performance.now();R.draw(s,1440,900,{exportFrame:false});gl.finish();timings.push(performance.now()-t);const raf=await new Promise(requestAnimationFrame);if(lastRaf!==null)rafPeriods.push(raf-lastRaf);lastRaf=raf;R.pollTimers();if(R.gpuMs!=null)gpu.push(R.gpuMs);}const firstDrawMs=timings[0],warmMax=Math.max(...timings.slice(5));timings.sort((a,b)=>a-b);gpu.sort((a,b)=>a-b);rafPeriods.sort((a,b)=>a-b);
  R.draw(s,720,450,{exportFrame:false,adaptiveScale:.5});const reducedBudget={width:R.renderInfo.internalWidth,height:R.renderInfo.internalHeight};if(reducedBudget.width*reducedBudget.height>1920*1080*.25)throw Error('Reduced preview budget exceeded');
  // The retained land mesh and analytic pack must not reveal a material square.
  const width=640,height=360,images=[];for(const geometryDetail of [true,false]){R.draw({...s,geometryDetail},width,height,{exportFrame:true});const bytes=new Uint8Array(width*height*4);gl.readPixels(0,0,width,height,gl.RGBA,gl.UNSIGNED_BYTE,bytes);images.push(bytes);}let landPixels=0,landTotal=0,landMax=0;const basis=M.basis(s.forward,s.up);
  for(let y=0;y<height;y++)for(let x=0;x<width;x++){const ray=M.ray((x+.5)/width*2-1,(y+.5)/height*2-1,width/height,s.fov,basis),t=M.shellDistance(s.position,ray,s.radius),q=M.norm(M.add(s.position,M.mul(ray,t))),sample=P.sample(q,s);if(!sample||Math.max(Math.abs(sample.x),Math.abs(sample.z))>318||sample.water.basin||sample.water.distance<5||P.model(s.provinceSeed).stations.some(p=>Math.hypot(p.x-sample.x,p.z-sample.z)<5))continue;landPixels++;for(let c=0;c<3;c++){const d=Math.abs(images[0][(y*width+x)*4+c]-images[1][(y*width+x)*4+c])/255;landTotal+=d;landMax=Math.max(landMax,d);}}
  const landAgreement={pixels:landPixels,mean:landTotal/(landPixels*3),max:landMax};
  const repeated=[];for(const seed of [714,715,713,714,713]){const v=SpherePacks.activate({...s,packAddress:null,provinceSeed:seed});const t=performance.now();await P.prepare(v);N.model(seed);repeated.push({seed,ms:performance.now()-t,province:P.info,pack:N.info});}await P.prepare(s);const warm=performance.now();await R.prepare(s);const cachedPrepareMs=performance.now()-warm;
  const q=P.direction(1100,400,s),f=P.frame(s),grazing={...s,position:M.mul(q,s.radius-48),forward:M.norm(M.add(f.basis[0],M.mul(q,.12))),up:f.basis[1],fov:110};await R.prepare(grazing);R.draw(grazing,1600,900,{exportFrame:true});const png=R.canvas.toDataURL();return {state:s,coldProvinceMs,uploadMs,cachedPrepareMs,probes,failures,traversal,repeated,landAgreement,reducedBudget,frames:{firstDrawMs,warmMax,rafMedian:rafPeriods[Math.floor(rafPeriods.length*.5)],rafP95:rafPeriods[Math.floor(rafPeriods.length*.95)],rafMax:rafPeriods.at(-1),median:timings[Math.floor(timings.length*.5)],p95:timings[Math.floor(timings.length*.95)],max:timings.at(-1),gpuMedian:gpu[Math.floor(gpu.length*.5)]},province:P.info,pack:N.info,gpuGeometry:{meshes:R.geometry.meshes.size,vertexMiB:[...R.geometry.meshes.keys()].reduce((n,m)=>n+m.vertices.byteLength,0)/1048576,pendingUploadBytes:[...R.geometry.meshes.entries()].reduce((n,[m,b])=>n+m.vertices.byteLength-b.offset,0)},render:R.renderInfo,error:R.error(),png};
 });fs.writeFileSync(path.join(dir,'grazing.png'),Buffer.from(audit.png.split(',')[1],'base64'));delete audit.png;fs.writeFileSync(path.join(dir,'audit.json'),JSON.stringify(audit,null,2));assert.equal(audit.error,0);assert.equal(audit.gpuGeometry.pendingUploadBytes,0);assert(audit.gpuGeometry.vertexMiB<=128);assert.deepEqual(audit.failures,[]);assert(audit.landAgreement.pixels>500);assert(audit.landAgreement.mean<.015,JSON.stringify(audit.landAgreement));for(const r of audit.traversal){assert(r.height>0&&r.height<.003);assert(r.playing&&r.addressEqual&&!r.autoSpeed);assert.equal(r.speed,.017);}console.log('PASS graph CPU/GPU masks and neighbourhood landings',audit.probes);
 const captures=[];for(const projection of ['perspective','panorama']){
  await page.evaluate(({state,projection})=>{SphereApp.setState({...state,projection});document.getElementById('exportSize').value='3840';}, {state:audit.state,projection});const pairs=[];
  for(let i=0;i<2;i++){const dl=page.waitForEvent('download');await page.evaluate(async()=>{SphereApp.setBusy(false);await SphereApp.capture();SphereApp.setBusy(true);});const files=unzip(fs.readFileSync(await(await dl).path()));pairs.push(files);fs.writeFileSync(path.join(dir,projection+'-'+i+'.png'),files['photograph.png']);fs.writeFileSync(path.join(dir,projection+'-'+i+'-scene.json'),files['scene.json']);}
  const metadata=JSON.parse(pairs[0]['scene.json']),equal=pairs[0]['photograph.png'].equals(pairs[1]['photograph.png']);captures.push({projection,equal,bytes:pairs[0]['photograph.png'].length,image:metadata.image,address:metadata.state.packAddress});assert.deepEqual(metadata.state.packAddress,audit.state.packAddress);console.log(projection,'capture equal',equal);
 }
 const report={coldStartupMs,audit,captures,errors};fs.writeFileSync(path.join(dir,'report.json'),JSON.stringify(report,null,2));assert(captures.every(c=>c.equal),'Cold/warm capture mismatch retained in evidence');assert.deepEqual(errors,[]);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
