const {chromium}=require(process.env.SPHERE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.SPHERE_BROWSER});try{
 const page=await browser.newPage({viewport:{width:1500,height:1300},acceptDownloads:true}),errors=[],dir=path.resolve('work/screenshots/places');fs.mkdirSync(dir,{recursive:true});page.setDefaultTimeout(180000);page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});
 await page.goto(process.env.SPHERE_URL||'http://127.0.0.1:8766/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.SphereLoading?.ready);await page.evaluate(()=>{SphereApp.setBusy(true);document.querySelector('[data-tab=camera]').click();});console.log('Places ready');
 assert.equal(await page.locator('#speedMode').inputValue(),'auto');assert.equal(await page.locator('#seeSurface').textContent(),'Go to pointer');assert(await page.locator('#browseBiomes').isDisabled());
 for(const category of ['biomes','watersheds','machinery','poles','shades','wounds']){await page.locator(`[data-category=${category}]`).click();assert.equal(await page.locator(`[data-category=${category}]`).getAttribute('aria-pressed'),'true');assert((await page.locator('#placeDestination option').count())>0);}
 assert(!(await page.getByText('Original study viewpoints',{exact:true}).isVisible()));assert(!(await page.getByText('Staged lighting studies',{exact:true}).isVisible()));
 await page.locator('[data-category=biomes]').click();await page.locator('#placeDestination').selectOption('biome-2');await page.locator('[name=placeScene][value=day]').check();await page.locator('[name=placeWeather][value=clear]').check();await page.locator('#visitPlace').click();await page.waitForFunction(()=>SphereApp.getState().walkMode);
 await page.evaluate(()=>{const s=SphereApp.getState();for(let i=0;i<180;i++)SphereSites.step(s,new Set(),1/60);SphereApp.setState(s);SphereApp.setPlaying(true);});
 const before=await page.evaluate(()=>SphereApp.getState());
 await page.locator('#viewport').focus();await page.keyboard.down('e');await page.keyboard.down('Space');await page.keyboard.up('Space');await page.keyboard.up('e');
 assert.equal(await page.evaluate(()=>SphereApp.getState().walkMode),false);assert(await page.evaluate(()=>SphereApp.getState().playing));await page.evaluate(()=>SphereApp.setBusy(false));await page.waitForFunction(()=>!SphereTravel.lifting);await page.evaluate(()=>SphereApp.setBusy(true));
 const after=await page.evaluate(()=>SphereApp.getState());assert(Math.abs(Math.hypot(...before.position.map((v,i)=>v-after.position[i]))-.045)<.00001);assert.equal(after.speed,before.speed);console.log('PASS category browser, landing, E + Space smooth lift-off and play preserved');
 await page.locator('#visitPlace').click();await page.waitForFunction(()=>SphereApp.getState().walkMode);await page.locator('#viewport').focus();await page.keyboard.down('Space');await page.keyboard.down('e');await page.keyboard.up('e');await page.keyboard.up('Space');assert(await page.evaluate(()=>SphereTravel.lifting));assert(await page.evaluate(()=>SphereApp.getState().playing));
 await page.evaluate(()=>SphereTravel.reset());
 // A marked point supplies a non-central pointer ray; pointer-browser also tests the real mouse path. Return is a separate history action.
 await page.evaluate(()=>{const M=SphereMath,s={...M.defaultState(),collection:true,routeShades:false},q=SphereWorld.locateBiome(2,s);s.position=M.mul(q,s.radius-100);s.forward=q;s.up=M.basis(q).u;SphereApp.setState(s);window.dispatchEvent(new Event('sphere-view-changed'));});
 const bounds=await page.locator('#view').boundingBox();await page.evaluate(()=>SpherePlaceBrowser.mark([.67,.46]));
 const pointer=await page.evaluate(()=>{const s=SphereApp.getState(),ray=SpherePlaceBrowser.pointerRay(s),t=SphereMath.sphereDistance(s.position,ray,[0,0,0],s.radius);return {state:s,q:SphereMath.norm(SphereMath.add(s.position,SphereMath.mul(ray,t)))};});
 await page.locator('#seeSurface').click();const selected=await page.evaluate(()=>SphereApp.getState());assert(Math.hypot(...SphereVectorDifference(selected.position.map(v=>v/Math.hypot(...selected.position)),pointer.q))<1e-10);assert.equal(await page.locator('#seeSurface').textContent(),'Go to pointer');
 await page.locator('[data-destination=overview]').click();await page.locator('#browseBiomes').click();const returned=await page.evaluate(()=>SphereApp.getState());assert.deepEqual(returned.position,selected.position);await page.locator('#browseBiomes').click();assert.deepEqual((await page.evaluate(()=>SphereApp.getState())).position,pointer.state.position);console.log('PASS off-centre pointer, one-way action and consecutive return history');
 await page.locator('#exactPosition summary').first().click();await page.locator('#speedMode').selectOption('manual');await page.locator('#speed').selectOption('1000');assert.equal(await page.evaluate(()=>SphereApp.getState().autoSpeed),false);await page.locator('#speedMode').selectOption('auto');assert(await page.locator('#speed').isDisabled());
 await page.locator('#exactPosition summary').first().click();
 await page.locator('[data-category=watersheds]').click();await page.locator('[data-arrival=atmosphere]').click();await page.locator('[name=placeWeather][value=mixed]').check();await page.locator('#visitPlace').click();await page.waitForFunction(()=>Math.abs(SphereApp.getState().radius-SphereMath.length(SphereApp.getState().position)-SpherePlaces.atmosphereKm)<.01);
 console.log('Atmosphere arrival ready');
 async function render(name){const out=await page.evaluate(async()=>{const A=SphereApp,s=A.getState(),R=A.renderer;await R.prepare(s);R.draw(s,1600,1000,{exportFrame:true});R.draw(s,1600,1000,{exportFrame:true});return {png:R.canvas.toDataURL(),error:R.error(),weather:R.renderInfo.weather,state:s};});fs.writeFileSync(path.join(dir,name+'.png'),Buffer.from(out.png.split(',')[1],'base64'));delete out.png;assert.equal(out.error,0);return out;}
 const depthCheck=await page.evaluate(()=>{const R=SphereApp.renderer,s=SphereApp.getState(),gl=R.gl,weather=R.weather,original=weather.farProgram;
  const debug=SphereVolume.far.replace('scattering=vec4(light,1.);transmission=vec4(tr,depth);','vec4 band=heightBand(d,low,high,1e20);scattering=vec4(hit-band.z,band.w-band.z,hit-band.w,1.);transmission=vec4(tr,depth);');
  weather.farProgram=SphereGLProgram(gl,SphereShaders.vertex,debug);R.draw(s,600,400,{exportFrame:true});gl.bindFramebuffer(gl.FRAMEBUFFER,weather.volumeFbo);gl.readBuffer(gl.COLOR_ATTACHMENT0);const pixels=[];
  for(const y of [.1,.5,.9])for(const x of [.1,.5,.9]){const out=new Float32Array(4);gl.readPixels(Math.floor(x*weather.vw),Math.floor(y*weather.vh),1,1,gl.RGBA,gl.FLOAT,out);pixels.push([...out]);}gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.deleteProgram(weather.farProgram.p);weather.farProgram=original;return pixels;
 });for(const pixel of depthCheck)assert(pixel[0]>0&&pixel[0]<10,'The cloud and surface depth must refer to the same ray: '+JSON.stringify(pixel));console.log('PASS cloud depth sampling across the entire view');
 const atmosphere=await render('atmosphere');
 await page.evaluate(()=>{document.getElementById('controls').scrollTop=0;document.getElementById('toast').classList.remove('visible');SphereApp.setPlaying(false);SphereApp.setBusy(false);});await page.waitForTimeout(800);await page.evaluate(()=>SphereApp.setBusy(true));await page.screenshot({path:path.join(dir,'explore.png')});
 await page.evaluate(()=>{SphereApp.setPlaying(true);document.getElementById('exportSize').value='3840';});const downloaded=page.waitForEvent('download');await page.evaluate(async()=>{SphereApp.setBusy(false);await SphereApp.capture();SphereApp.setBusy(true);});const files=unzip(fs.readFileSync(await (await downloaded).path())),photo=JSON.parse(files['scene.json']);assert.equal(photo.image.width,3840);assert.equal(photo.state.placeWeather,'mixed');assert.equal(photo.state.autoSpeed,true);assert(await page.evaluate(()=>SphereApp.getState().playing));fs.writeFileSync(path.join(dir,'atmosphere-4k.png'),files['photograph.png']);fs.writeFileSync(path.join(dir,'atmosphere-4k.json'),files['scene.json']);
 await page.locator('[data-arrival=clouds]').click();await page.locator('[name=placeScene][value=first-light]').check();await page.locator('[name=placeWeather][value=storm]').check();await page.locator('#visitPlace').click();await page.waitForFunction(()=>SphereApp.getState().placeWeather==='storm');const storm=await render('storm');
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(dir,'verification.json'),JSON.stringify({before,after,pointer,selected,returned,atmosphere,depthCheck,photo:photo.image,storm,errors},null,2));console.log('PASS distant cloud, 4K photograph and local storm rendering, no WebGL or page errors');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
function SphereVectorDifference(a,b){return a.map((v,i)=>v-b[i]);}
function unzip(bytes){const files={};let p=0;while(p+30<=bytes.length&&bytes.readUInt32LE(p)===0x04034b50){const size=bytes.readUInt32LE(p+18),n=bytes.readUInt16LE(p+26),extra=bytes.readUInt16LE(p+28),name=bytes.subarray(p+30,p+30+n).toString(),start=p+30+n+extra;files[name]=bytes.subarray(start,start+size);p=start+size;}return files;}
