const {chromium}=require(process.env.SPHERE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.SPHERE_BROWSER});try{
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],dir=path.resolve('work/screenshots/pointer');fs.mkdirSync(dir,{recursive:true});page.setDefaultTimeout(180000);page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8766/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.SphereLoading?.ready);
 const ready=async()=>{await page.waitForFunction(()=>SphereLoading.ready||SphereLoading.error);assert.equal(await page.evaluate(()=>SphereLoading.error),null);};
 async function scene(extra={}){await page.evaluate(extra=>{const M=SphereMath,s={...M.defaultState(),collection:true,routeShades:false,geometryDetail:false,atmosphere:0,cavityHaze:0,clouds:false,...extra},q=SphereWorld.locateBiome(2,s);s.position=M.mul(q,s.radius-100);s.forward=q;s.up=M.basis(q).u;SphereApp.setState(s);},extra);await ready();await page.waitForTimeout(100);}
 await scene();let r=await page.locator('#view').boundingBox();await page.mouse.click(r.x+r.width*.35,r.y+r.height*.62);const marked=await page.evaluate(()=>({picked:SpherePlaceBrowser.picked,left:document.querySelector('.pointer-aim').style.left,top:document.querySelector('.pointer-aim').style.top}));assert.equal(marked.picked.type,'shell');
 const b=await page.locator('#seeSurface').boundingBox();await page.mouse.move(b.x+b.width*.5,b.y+b.height*.5,{steps:35});const reached=await page.evaluate(()=>({picked:SpherePlaceBrowser.picked,left:document.querySelector('.pointer-aim').style.left,top:document.querySelector('.pointer-aim').style.top}));assert.deepEqual(reached,marked,'Crossing the canvas to the button must not move the pin');
 await page.locator('#seeSurface').click();await ready();const arrived=await page.evaluate(()=>SphereApp.getState());close(unit(arrived.position),marked.picked.selected);close(arrived.forward,marked.picked.selected);console.log('PASS actual mouse path to the button preserves the selected place');
 await page.locator('#browseBiomes').click();await ready();r=await page.locator('#view').boundingBox();await page.mouse.move(r.x+r.width*.69,r.y+r.height*.36);const expected=await page.evaluate(()=>{const s=SphereApp.getState(),ray=SpherePlaceBrowser.pointerRay(s,[.69,.36]);return SpherePointer.pick(s,ray).selected;});await page.keyboard.press('g');await ready();close(unit((await page.evaluate(()=>SphereApp.getState())).position),expected);console.log('PASS G travels to the actual mouse position');
 await scene();r=await page.locator('#view').boundingBox();await page.mouse.click(r.x+r.width*.3,r.y+r.height*.4);assert(await page.evaluate(()=>!!SpherePlaceBrowser.picked));await page.mouse.move(r.x+r.width*.5,r.y+r.height*.5);await page.mouse.down();await page.mouse.move(r.x+r.width*.56,r.y+r.height*.55,{steps:12});await page.mouse.up();assert.equal(await page.evaluate(()=>SpherePlaceBrowser.picked),null);console.log('PASS dragging to look invalidates the old marker');
 // Enter a central Wound with the real button, turn back through its aperture,
 // and leave for the visible far wall. Keep the prepared spill geometry active.
 await page.evaluate(()=>{const M=SphereMath,w=SphereCollection.wounds[0],s={...M.defaultState(),collection:true,routeShades:false,geometryDetail:false,atmosphere:0,cavityHaze:0,clouds:false};s.position=M.mul(w.axis,s.radius-10000);s.forward=w.axis;s.up=M.basis(w.axis).u;SphereApp.setState(s);SphereApp.setPlaying(true);});await ready();
 r=await page.locator('#view').boundingBox();await page.mouse.click(r.x+r.width*.5,r.y+r.height*.5);await page.locator('#seeSurface').click();await ready();
 const spill=await page.evaluate(()=>SphereApp.getState());assert.equal(spill.siteId,'exterior-0');assert.equal(spill.geometryDetail,true);assert.equal(spill.playing,true);await page.screenshot({path:path.join(dir,'wound-spill.png')});
 await page.evaluate(()=>{const M=SphereMath,w=SphereCollection.wounds[0],s=SphereApp.getState();s.forward=M.norm(M.add(M.mul(w.axis,-1),M.mul(w.tangent,.15)));s.up=M.basis(s.forward,s.up).u;SphereApp.setState(s);});await ready();
 const exitView=await page.evaluate(()=>{const s=SphereApp.getState(),ray=SpherePlaceBrowser.pointerRay(s,[.5,.5]);return {state:s,visible:SphereSites.trace(s.position,ray,s,SphereMath.trace)};});assert.equal(exitView.visible.kind,'Inner surface');
 r=await page.locator('#view').boundingBox();await page.mouse.click(r.x+r.width*.5,r.y+r.height*.5);const exitTarget=await page.evaluate(()=>SpherePlaceBrowser.picked);assert.equal(exitTarget.type,'shell');close(exitTarget.selected,unit(exitView.visible.point));await page.screenshot({path:path.join(dir,'wound-exit-target.png')});
 await page.locator('#seeSurface').click();await ready();await page.waitForTimeout(500);const exitArrival=await page.evaluate(()=>SphereApp.getState());close(unit(exitArrival.position),exitTarget.selected);assert.equal(exitArrival.siteId,'');assert.equal(exitArrival.siteAnchor,null);assert.equal(exitArrival.playing,true);assert.equal(await page.evaluate(()=>SpherePlaceBrowser.picked),null);
 await page.locator('#browseBiomes').click();await ready();const returnedSpill=await page.evaluate(()=>SphereApp.getState());assert.deepEqual(returnedSpill.position,exitView.state.position);assert.equal(returnedSpill.siteId,'exterior-0');assert.equal(returnedSpill.playing,true);
 // G over an empty far aperture must not fall back to the unrelated centre hit.
 const openPoint=await page.evaluate(()=>{const M=SphereMath,s=SphereApp.getState(),far=SphereCollection.wounds[1],ray=M.norm(M.sub(M.mul(far.axis,s.radius),s.position)),wall=s.forward;s.forward=M.norm(M.add(wall,ray));s.up=M.norm(M.cross(wall,ray));SphereApp.setState(s);const b=M.basis(s.forward,s.up),x=M.dot(ray,b.r)/(M.dot(ray,b.f)*Math.tan(M.radians(s.fov)*.5));return [(x+1)*.5,.5];});await ready();assert(openPoint[0]>0&&openPoint[0]<1);
 const openView=await page.evaluate(point=>{const s=SphereApp.getState();return {state:s,empty:SpherePointer.pick(s,SpherePlaceBrowser.pointerRay(s,point)),centre:SpherePointer.pick(s,SpherePlaceBrowser.pointerRay(s,[.5,.5]))};},openPoint);assert.equal(openView.empty,null);assert.equal(openView.centre.type,'shell');
 r=await page.locator('#view').boundingBox();await page.locator('#viewport').focus();await page.mouse.move(r.x+r.width*openPoint[0],r.y+r.height*openPoint[1]);await page.keyboard.press('g');await page.waitForTimeout(150);assert.deepEqual((await page.evaluate(()=>SphereApp.getState())).position,openView.state.position);assert.equal(await page.evaluate(()=>SpherePlaceBrowser.picked),null);
 await page.locator('[data-tab=camera]').click();await page.locator('[data-category=biomes]').click();await page.locator('#placeDestination').selectOption('biome-2');await page.locator('[data-arrival=atmosphere]').click();await page.locator('[name=placeWeather][value=clear]').check();await page.locator('#visitPlace').click();await page.waitForFunction(()=>SphereApp.getState().siteId==='');await ready();
 const menuExit=await page.evaluate(()=>{const s=SphereApp.getState();return {state:s,biome:SphereWorld.sample(SphereMath.norm(s.position),s).id,altitude:s.radius-SphereMath.length(s.position),expected:SpherePlaces.atmosphereKm};});assert.equal(menuExit.biome,2);assert(Math.abs(menuExit.altitude-menuExit.expected)<.001);assert.equal(menuExit.state.playing,true);assert.equal(await page.evaluate(()=>SpherePlaceBrowser.picked),null);await page.evaluate(()=>SphereApp.setPlaying(false));
 const wound={spill,exitView,exitTarget,exitArrival,returnedSpill,openPoint,openView,menuExit};console.log('PASS central Wound entry, far-wall exit, empty-aperture G, return and Places visit without looping or changing play status');
 // A moving Shade retains a local address from marking until travel.
 await page.evaluate(()=>{const M=SphereMath,s={...M.defaultState(),collection:true,geometryDetail:false,atmosphere:0,cavityHaze:0,clouds:false,shadeShape:'disk'},p=SphereCollection.plates(s).find(p=>!p.damage);s.position=M.add(M.mul(p.center,s.radius),M.mul(p.normal,1));s.forward=M.mul(p.normal,-1);s.up=p.up;SphereApp.setState(s);});await ready();r=await page.locator('#view').boundingBox();await page.mouse.click(r.x+r.width*.5,r.y+r.height*.5);const shade=await page.evaluate(()=>SpherePlaceBrowser.picked);assert.equal(shade.type,'shade');await page.evaluate(()=>{const s=SphereApp.getState();s.time+=240;SphereApp.setState(s);});await ready();await page.locator('#seeSurface').click();await ready();const shadeArrival=await page.evaluate(()=>{const s=SphereApp.getState(),p=SphereCollection.plates(s).find(p=>p.id===s.shadeAttachment);return {state:s,centre:SphereMath.mul(p.center,s.radius)};});assert.equal(shadeArrival.state.shadeAttachment,shade.plate);assert(Math.hypot(...shadeArrival.state.position.map((v,i)=>v-shadeArrival.centre[i]))<.06);console.log('PASS marked Shade location follows its motion');
 const checked=await page.evaluate(()=>({gl:SphereApp.renderer.error(),info:SphereApp.renderer.renderInfo}));assert.equal(checked.gl,0);assert.deepEqual(errors,[]);await page.screenshot({path:path.join(dir,'shade-arrival.png')});fs.writeFileSync(path.join(dir,'verification.json'),JSON.stringify({marked,arrived,wound,shade,shadeArrival,checked,errors},null,2));console.log('PASS pointer browser, history and no rendering errors');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
function unit(v){const r=Math.hypot(...v);return v.map(x=>x/r);}function close(a,b){assert(Math.hypot(...a.map((v,i)=>v-b[i]))<1e-8,JSON.stringify({a,b}));}
