const {chromium}=require(process.env.SPHERE_PLAYWRIGHT||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const dir=path.resolve('work/screenshots/polish');fs.mkdirSync(dir,{recursive:true});const profile=fs.mkdtempSync(path.join(dir,'session-profile-')),url=process.env.SPHERE_URL||'http://127.0.0.1:8766/',errors=[];
 const launch=()=>chromium.launchPersistentContext(profile,{headless:true,executablePath:process.env.SPHERE_BROWSER,viewport:{width:1500,height:1000}});
 let context=await launch();try{
  let page=context.pages()[0];page.setDefaultTimeout(120000);page.on('pageerror',e=>errors.push(e.message));await page.goto(url,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.SphereSession);console.log('First session ready');
  await page.evaluate(()=>{SphereEvolution.visit('shade-7');const s=SphereApp.getState();Object.assign(s,{exposure:-.7,time:23456,timeRate:600,weatherStrength:.81,weatherQuality:2,cavityHaze:.43,atmosphere:.73,richMaterials:true,localShadows:2,surfaceLock:false,fov:91,quality:.75});SphereApp.setState(s);});
  await page.click('[data-tab="lighting"]');await page.selectOption('#previewFps','30');await page.uncheck('#adaptivePreview');await page.selectOption('#exportSize','3840',{force:true});
  await page.evaluate(()=>{for(const [id,value] of [['fieldDestination','port-1'],['biomeDestination','7'],['biomeAltitude','100']]){const e=document.getElementById(id);e.value=value;e.dispatchEvent(new Event('change',{bubbles:true}));}});
  await page.click('#fullscreen');await page.click('#flightConsoleButton');await page.selectOption('#consoleAntialias','2');assert.equal(await page.evaluate(()=>SphereApp.getState().antialias),2);await page.selectOption('#consoleAntialias','3');assert.equal(await page.locator('#antialias').inputValue(),'3');
  await page.locator('#viewport').focus();await page.keyboard.press('Space');assert(await page.evaluate(()=>SphereApp.getState().playing));await page.waitForTimeout(180);await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>SphereApp.getState().playing),false);
  await page.screenshot({path:path.join(dir,'fullscreen-settings.png')});await page.evaluate(()=>document.exitFullscreen());
  await page.waitForFunction(()=>{const raw=localStorage.getItem(SphereSession.key);if(!raw)return false;const saved=JSON.parse(raw),s=SphereApp.getState();return saved.state.time===s.time&&saved.state.antialias===3&&saved.ui.values.adaptivePreview===false&&saved.ui.values.exportSize==='3840';});
  const saved=await page.evaluate(()=>({state:SphereApp.getState(),record:JSON.parse(localStorage.getItem(SphereSession.key))}));await context.close();context=await launch();page=context.pages()[0];page.setDefaultTimeout(120000);page.on('pageerror',e=>errors.push(e.message));await page.goto(url,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.SphereSession);console.log('Restarted session ready');
  const restored=await page.evaluate(()=>({state:SphereApp.getState(),restored:SphereSession.restored,values:Object.fromEntries(['previewFps','adaptivePreview','exportSize','fieldDestination','biomeDestination','biomeAltitude','consoleAntialias'].map(id=>{const el=document.getElementById(id);return [id,el.type==='checkbox'?el.checked:el.value];})),tab:document.querySelector('[data-tab].active').dataset.tab}));
  assert(restored.restored);for(const key of ['exposure','time','timeRate','weatherStrength','weatherQuality','cavityHaze','atmosphere','richMaterials','localShadows','surfaceLock','fov','quality','shadeAttachment','siteId','antialias'])assert.equal(restored.state[key],saved.state[key],key);assert.equal(restored.state.playing,false);assert.deepEqual(restored.state.position,saved.state.position);assert.equal(restored.tab,'lighting');assert.deepEqual(restored.values,{previewFps:'30',adaptivePreview:false,exportSize:'3840',fieldDestination:'port-1',biomeDestination:'7',biomeAltitude:'100',consoleAntialias:'3'});
  // An immediate navigation must flush a pending camera/settings change.
  await page.evaluate(()=>{const s=SphereApp.getState();s.exposure=.9;SphereApp.setState(s);location.href='/work/screenshots/polish/review.html';});await page.waitForURL('**/review.html');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('sphere-session-v1')).state.exposure),.9);
  for(const id of ['rim-air','rim-clear-clouds','shade-inspect','shade-fleet']){await page.selectOption('#scene',id);await page.waitForFunction(()=>[...document.querySelectorAll('img')].every(i=>i.complete&&i.naturalWidth===1600));}await page.selectOption('#scene','rim-air');await page.locator('#split').evaluate(el=>{el.value='55';el.dispatchEvent(new Event('input'));});assert((await page.locator('#after').getAttribute('style')).includes('55%'));await page.selectOption('#zoom','2');assert((await page.locator('#canvas').getAttribute('style')).includes('200%'));await page.selectOption('#zoom','1');await page.screenshot({path:path.join(dir,'review-ui.png')});
  fs.writeFileSync(path.join(dir,'session-verification.json'),JSON.stringify({saved,restored,spaceToggled:true,immediateNavigationFlushed:true,comparisonViews:4,errors},null,2));assert.deepEqual(errors,[]);console.log('PASS browser restart restores scene and UI settings, fullscreen AA controls, existing Space play/pause, pagehide flush and comparison review');
 }finally{await context.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
