const assert=require('node:assert/strict'),M=require('../math.js');require('../collection.js');require('../biomes.js');require('../world-palette.js');require('../world.js');require('../field-sites.js');require('../watershed-network.js');require('../watershed-province.js');require('../flight.js');require('../session-state.js');
const P=SphereWatershed,W=SphereWorld,S=SphereSites,base={...M.defaultState(),collection:true,era:'after'};
// Missing province fields in either historical layout never move its camera or
// acquire new geography. The extension is separately versioned and opt-in.
for(const layoutVersion of [1,2]){const input={...base,layoutVersion};for(const key of ['provinceRevision','provinceSeed','provinceAnchor'])delete input[key];const s=M.validate(input);assert.equal(s.provinceRevision,0);assert.deepEqual(s.position,input.position);assert.deepEqual(P.geometry(s),[]);}
const s=P.activate(base),serialized=M.sceneRecord(s).state;assert.equal(s.provinceRevision,1);assert.equal(base.provinceRevision,0);assert.deepEqual(M.validate(serialized),s);assert.deepEqual(SphereSessionCodec.decode(SphereSessionCodec.encode(s,{})).state.provinceAnchor,s.provinceAnchor);
for(const patch of [{provinceRevision:2},{provinceRevision:.5},{provinceSeed:-1},{provinceSeed:1.5},{provinceAnchor:[1,0,1]},{provinceAnchor:null},{layoutVersion:1},{collection:false}])assert.throws(()=>M.validate({...s,...patch}));
let addresses=0;for(const radius of [M.AU*.5,M.AU,M.AU*2])for(const [x,z]of [[0,0],[300,-300],[-250,180],[23,-106]]){const v={...s,radius},q=P.direction(x,z,v),found=P.local(q,v);assert(Math.hypot(found[0]-x,found[1]-z)<1e-6);const a=P.sample(q,v);assert.equal(a.originalBiome,W.sample(q,v).id);assert.equal(a.damage,W.sample(q,v).damage);addresses++;}
for(const seed of [0,713,827,341,902,2147483647]){const p=P.model(seed);assert(p.focus);assert(p.stations.length>=3);for(const station of p.stations){const water=p.water(station.x,station.z);assert(!water.river&&!water.basin,'Facilities need dry banks');}assert(p.height(320,0)<1e-12);}
assert.deepEqual([...new Set(P.model(713).stations.map(s=>s.role))].sort(),['Fabrication','Reserve storage','Thermal transfer','Water recovery']);
const groups=P.geometry(s),land=groups[0],packed=S.packBVH(land.triangles);let rays=0;
for(let x=-220;x<220;x+=23)for(let z=-220;z<220;z+=27){const pos=[x,5,z],dir=[0,-1,0],a=S.rayBVH(pos,dir,land.bvh,Infinity),b=S.rayBVH(pos,dir,packed,Infinity);assert.equal(a,b);assert(a>0&&a<5);rays++;}
for(const name of ['province','approach','garden','terrace']){const v=P.view(s,name),hit=S.trace(v.position,v.forward,v,M.trace);assert(hit.kind.startsWith('Watershed'));assert(Number.isFinite(hit.distance));if(['garden','terrace'].includes(name)){const a=P.sample(M.norm(v.position),v),f=P.model(v.provinceSeed).focus;assert(Math.hypot(a.x-f.x,a.z-f.z)<2,'Close arrivals must share the approach address, even when facility names repeat');}assert.equal(M.validate(M.sceneRecord(v).state).provinceRevision,1);}
const terrace=P.view(s,'terrace'),down=M.norm(terrace.position),contact=SphereFlight.contact(terrace,terrace.position,down,.1);assert(contact.kind.startsWith('Watershed'));assert(Math.abs(contact.distance-.004)<.00005,'Six-metre terrace arrival retains two-metre flight clearance');
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');let packet;
const worker=vm.createContext({postMessage:data=>{packet=data;}});worker.importScripts=(...files)=>files.forEach(file=>vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),worker));vm.runInContext(fs.readFileSync(path.join(__dirname,'../watershed-worker.js'),'utf8'),worker);worker.onmessage({data:s});assert(!packet.error,packet.error);assert.equal(packet.groups.length,groups.length);
for(let i=0;i<groups.length;i++){assert(Buffer.from(packet.groups[i].vertices.buffer).equals(Buffer.from(groups[i].vertices.buffer)),'Worker and synchronous capture must generate identical triangles');assert.equal(packet.groups[i].bvh.packedTriangles.length,groups[i].count*3);}
const segments=P.model(713).segments;for(let i=1;i<segments.length;i++)if(segments[i-1].b===segments[i].a){assert.deepEqual(segments[i-1].banks.slice(2),segments[i].banks.slice(0,2),'River bends must share both banks without wedges');}
// Changing the attack overlay does not rewrite the original biome or catchment.
const f=W.rimFrame(s,1,0),damaged={...s,provinceAnchor:M.norm(M.add(f.point,M.mul(f.inland,120/s.radius)))},q=damaged.provinceAnchor,a=P.sample(q,damaged),b=P.sample(q,{...damaged,era:'before'});assert(a.damage>b.damage);assert.equal(a.originalBiome,b.originalBiome);assert.equal(a.terrainKm,b.terrainKm);assert.deepEqual(a.water,b.water);
console.log(`PASS Watershed revision migration, invalid-state rejection, ${addresses} world addresses, six deterministic catchments, ${rays} shared collision rays, four arrivals, terrace flight contact, worker/capture byte parity, joined river banks and independent damage.`);
