const fs=require('node:fs'),path=require('node:path'),dir=path.resolve('work/screenshots/polish');
fs.mkdirSync(dir,{recursive:true});
fs.writeFileSync(path.join(dir,'review.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Observatory · air and edges</title><style>
*{box-sizing:border-box}body{margin:0;background:#10191d;color:#dde4df;font:15px/1.55 system-ui,sans-serif}main{max-width:1600px;margin:auto;padding:28px}header{display:flex;align-items:end;justify-content:space-between;gap:24px;margin-bottom:22px}h1{font-size:30px;font-weight:450;margin:4px 0}.eyebrow{color:#d7b785;font-size:11px;letter-spacing:.2em}p{color:#a8b7b9;margin:4px 0}.controls{display:flex;gap:12px}label{font-size:12px}select{display:block;margin-top:5px;background:#1b2a30;color:inherit;font:inherit;padding:9px;border:1px solid #526465;border-radius:4px}.scroll{overflow:auto;max-height:calc(100vh - 310px);border:1px solid #526465;background:#000}.canvas{position:relative;width:100%;aspect-ratio:16/9}img{display:block;width:100%;height:100%}#after{position:absolute;inset:0;clip-path:inset(0 0 0 50%)}#line{position:absolute;inset:0 auto 0 50%;border-left:2px solid #dbc69b;pointer-events:none}.slider{display:flex;gap:18px;align-items:center;margin:15px 0;font-size:13px}input{flex:1;accent-color:#d7b785}footer{display:flex;justify-content:space-between;gap:24px;font-size:13px;margin-top:20px}a{color:#ddc298}small{color:#97abad}@media(max-width:800px){header,footer{display:block}.controls{margin-top:16px}main{padding:18px}h1{font-size:25px}.scroll{max-height:65vh}}
</style><main><header><div><div class="eyebrow">THE SPHERE · OBSERVATORY 1.4</div><h1>Clearer edges. Continuous air.</h1><p>The same camera and exposure, before and after this pass.</p></div><div class="controls"><label>Reference view<select id="scene"><option value="rim-air">Wound · clouds and air</option><option value="rim-clear-clouds">Wound · air alone</option><option value="shade-inspect">Shade · grazing view</option><option value="shade-fleet">Shade · distant fleet</option></select></label><label>Zoom<select id="zoom"><option value="1">Fit</option><option value="2">2×</option><option value="4">4×</option></select></label></div></header>
<div class="scroll" id="scroll"><div class="canvas" id="canvas"><img id="before" alt="Observatory 1.3"><img id="after" alt="Observatory 1.4"><div id="line"></div></div></div><label class="slider"><span>Before · 1.3</span><input id="split" type="range" min="0" max="100" value="50" aria-label="Comparison divider"><span>After · 1.4</span></label><small>These 1600 × 900 views use the same Smooth edges setting with the preview below its supersampling budget. Zoom and scroll to inspect individual silhouettes. The full application also supports native 4K photographs.</small>
<footer><a href="/">Return to the Observatory →</a><span><a href="verification.json">Verification and timings</a> · <a href="/docs/Observatory-Polish-14.md">Implementation notes</a></span></footer></main><script>
const $=id=>document.getElementById(id);function scene(){for(const id of ['before','after'])$(id).src=id+'/'+$('scene').value+'.png';$('zoom').value='1';zoom();}function zoom(){const z=Number($('zoom').value);$('canvas').style.width=z*100+'%';const p=$('scene').value.startsWith('rim')?[.57,.45]:[.55,.18];$('scroll').scrollLeft=p[0]*$('canvas').clientWidth-$('scroll').clientWidth/2;$('scroll').scrollTop=p[1]*$('canvas').clientHeight-$('scroll').clientHeight/2;}function split(){const value=$('split').value;$('after').style.clipPath='inset(0 0 0 '+value+'%)';$('line').style.left=value+'%';}$('scene').onchange=scene;$('zoom').onchange=zoom;$('split').oninput=split;scene();
</script></html>`);console.log(path.join(dir,'review.html'));
